#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int ua_iam_slide_in_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ua_iam_slide_in_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ua_iam_slide_out_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ua_iam_slide_out_top = 2130968579;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010017
			public const int bannerActionButtonTextAppearance = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int bannerDismissButtonDrawable = 2130771989;
			
			// aapt resource value: 0x7f010011
			public const int bannerFontPath = 2130771985;
			
			// aapt resource value: 0x7f010016
			public const int bannerNoDismissButton = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int bannerPrimaryColor = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int bannerSecondaryColor = 2130771988;
			
			// aapt resource value: 0x7f010012
			public const int bannerTextAppearance = 2130771986;
			
			// aapt resource value: 0x7f01000b
			public const int buttonSize = 2130771979;
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010010
			public const int circleCrop = 2130771984;
			
			// aapt resource value: 0x7f01000c
			public const int colorScheme = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public const int imageAspectRatio = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int imageAspectRatioAdjust = 2130771982;
			
			// aapt resource value: 0x7f010027
			public const int inAppMessageBannerStyle = 2130772007;
			
			// aapt resource value: 0x7f010022
			public const int messageCenterDividerColor = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int messageCenterEmptyMessageText = 2130772001;
			
			// aapt resource value: 0x7f010020
			public const int messageCenterEmptyMessageTextAppearance = 2130772000;
			
			// aapt resource value: 0x7f01001b
			public const int messageCenterItemBackground = 2130771995;
			
			// aapt resource value: 0x7f01001d
			public const int messageCenterItemDateTextAppearance = 2130771997;
			
			// aapt resource value: 0x7f010023
			public const int messageCenterItemIconEnabled = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int messageCenterItemIconPlaceholder = 2130772004;
			
			// aapt resource value: 0x7f01001c
			public const int messageCenterItemTitleTextAppearance = 2130771996;
			
			// aapt resource value: 0x7f010028
			public const int messageCenterStyle = 2130772008;
			
			// aapt resource value: 0x7f01001f
			public const int messageNotSelectedText = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int messageNotSelectedTextAppearance = 2130771998;
			
			// aapt resource value: 0x7f010029
			public const int mixed_content_mode = 2130772009;
			
			// aapt resource value: 0x7f010018
			public const int optCardBackgroundColor = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int optCardCornerRadius = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int optCardElevation = 2130771994;
			
			// aapt resource value: 0x7f01000d
			public const int scopeUris = 2130771981;
			
			// aapt resource value: 0x7f010025
			public const int ua_state_highlighted = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int urbanAirshipFontPath = 2130772006;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int cardview_dark_background = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int cardview_light_background = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int cardview_shadow_end_color = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int cardview_shadow_start_color = 2131230723;
			
			// aapt resource value: 0x7f08000c
			public const int common_action_bar_splitter = 2131230732;
			
			// aapt resource value: 0x7f080018
			public const int common_google_signin_btn_text_dark = 2131230744;
			
			// aapt resource value: 0x7f08000d
			public const int common_google_signin_btn_text_dark_default = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int common_google_signin_btn_text_dark_disabled = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int common_google_signin_btn_text_dark_focused = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int common_google_signin_btn_text_dark_pressed = 2131230734;
			
			// aapt resource value: 0x7f080019
			public const int common_google_signin_btn_text_light = 2131230745;
			
			// aapt resource value: 0x7f080011
			public const int common_google_signin_btn_text_light_default = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int common_google_signin_btn_text_light_disabled = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int common_google_signin_btn_text_light_focused = 2131230740;
			
			// aapt resource value: 0x7f080012
			public const int common_google_signin_btn_text_light_pressed = 2131230738;
			
			// aapt resource value: 0x7f08001a
			public const int common_plus_signin_btn_text_dark = 2131230746;
			
			// aapt resource value: 0x7f080004
			public const int common_plus_signin_btn_text_dark_default = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int common_plus_signin_btn_text_dark_disabled = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int common_plus_signin_btn_text_dark_focused = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int common_plus_signin_btn_text_dark_pressed = 2131230725;
			
			// aapt resource value: 0x7f08001b
			public const int common_plus_signin_btn_text_light = 2131230747;
			
			// aapt resource value: 0x7f080008
			public const int common_plus_signin_btn_text_light_default = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int common_plus_signin_btn_text_light_disabled = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int common_plus_signin_btn_text_light_focused = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int common_plus_signin_btn_text_light_pressed = 2131230729;
			
			// aapt resource value: 0x7f080015
			public const int ua_iam_primary = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int ua_iam_secondary = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int urban_airship_blue = 2131230743;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int cardview_compat_inset_shadow = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int cardview_default_elevation = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int cardview_default_radius = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int ua_iam_banner_corner_radius = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int ua_iam_banner_elevation = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int ua_iam_banner_width = 2131296261;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Icon = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ua_iam_background = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ua_ic_close = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ua_ic_close_white_18dp = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ua_ic_image_placeholder = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ua_ic_notification_button_accept = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ua_ic_notification_button_add = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ua_ic_notification_button_book = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ua_ic_notification_button_cart = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ua_ic_notification_button_copy = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ua_ic_notification_button_decline = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ua_ic_notification_button_download = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ua_ic_notification_button_event = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ua_ic_notification_button_follow = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ua_ic_notification_button_happy = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ua_ic_notification_button_info = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ua_ic_notification_button_open_browser = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ua_ic_notification_button_remind = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ua_ic_notification_button_sad = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ua_ic_notification_button_save = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ua_ic_notification_button_search = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ua_ic_notification_button_send = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ua_ic_notification_button_share = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ua_ic_notification_button_thumbs_down = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ua_ic_notification_button_thumbs_up = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ua_ic_notification_button_unfollow = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ua_ic_urbanairship_notification = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ua_item_mc_background = 2130837573;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0e0015
			public const int action_button = 2131623957;
			
			// aapt resource value: 0x7f0e0019
			public const int action_buttons = 2131623961;
			
			// aapt resource value: 0x7f0e0018
			public const int action_divider = 2131623960;
			
			// aapt resource value: 0x7f0e0006
			public const int adjust_height = 2131623942;
			
			// aapt resource value: 0x7f0e0007
			public const int adjust_width = 2131623943;
			
			// aapt resource value: 0x7f0e0017
			public const int alert = 2131623959;
			
			// aapt resource value: 0x7f0e0009
			public const int always_allow = 2131623945;
			
			// aapt resource value: 0x7f0e0003
			public const int auto = 2131623939;
			
			// aapt resource value: 0x7f0e000c
			public const int channel_id = 2131623948;
			
			// aapt resource value: 0x7f0e001a
			public const int checkbox = 2131623962;
			
			// aapt resource value: 0x7f0e0016
			public const int close = 2131623958;
			
			// aapt resource value: 0x7f0e000d
			public const int close_button = 2131623949;
			
			// aapt resource value: 0x7f0e000a
			public const int compatibility_mode = 2131623946;
			
			// aapt resource value: 0x7f0e0010
			public const int container = 2131623952;
			
			// aapt resource value: 0x7f0e0004
			public const int dark = 2131623940;
			
			// aapt resource value: 0x7f0e001c
			public const int date = 2131623964;
			
			// aapt resource value: 0x7f0e001f
			public const int delete = 2131623967;
			
			// aapt resource value: 0x7f0e0012
			public const int error = 2131623954;
			
			// aapt resource value: 0x7f0e0000
			public const int icon_only = 2131623936;
			
			// aapt resource value: 0x7f0e001d
			public const int image = 2131623965;
			
			// aapt resource value: 0x7f0e000e
			public const int in_app_message = 2131623950;
			
			// aapt resource value: 0x7f0e0005
			public const int light = 2131623941;
			
			// aapt resource value: 0x7f0e001e
			public const int mark_read = 2131623966;
			
			// aapt resource value: 0x7f0e0011
			public const int message_container = 2131623953;
			
			// aapt resource value: 0x7f0e000f
			public const int message_list_container = 2131623951;
			
			// aapt resource value: 0x7f0e000b
			public const int never_allow = 2131623947;
			
			// aapt resource value: 0x7f0e0008
			public const int none = 2131623944;
			
			// aapt resource value: 0x7f0e0013
			public const int retry_button = 2131623955;
			
			// aapt resource value: 0x7f0e0020
			public const int select_all = 2131623968;
			
			// aapt resource value: 0x7f0e0001
			public const int standard = 2131623937;
			
			// aapt resource value: 0x7f0e0014
			public const int swipe_container = 2131623956;
			
			// aapt resource value: 0x7f0e001b
			public const int title = 2131623963;
			
			// aapt resource value: 0x7f0e0002
			public const int wide = 2131623938;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int google_play_services_version = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int ua_iam_animation_duration = 2131427329;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ua_activity_landing_page = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ua_fragment_iam = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ua_fragment_iam_card = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ua_fragment_mc = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ua_fragment_message = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ua_fragment_message_list = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ua_fragment_no_message_selected = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ua_iam_button = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ua_iam_content = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ua_item_mc = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ua_item_mc_content = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ua_item_mc_icon_content = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0d0000
			public const int ua_mc_action_mode = 2131558400;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f0c0000
			public const int ua_selected_count = 2131492864;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int ua_native_bridge = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a004d
			public const int app_name = 2131361869;
			
			// aapt resource value: 0x7f0a001d
			public const int auth_google_play_services_client_facebook_display_name = 2131361821;
			
			// aapt resource value: 0x7f0a001c
			public const int auth_google_play_services_client_google_display_name = 2131361820;
			
			// aapt resource value: 0x7f0a0015
			public const int common_google_play_services_api_unavailable_text = 2131361813;
			
			// aapt resource value: 0x7f0a0007
			public const int common_google_play_services_enable_button = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int common_google_play_services_enable_text = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int common_google_play_services_enable_title = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int common_google_play_services_install_button = 2131361796;
			
			// aapt resource value: 0x7f0a0002
			public const int common_google_play_services_install_text_phone = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int common_google_play_services_install_text_tablet = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int common_google_play_services_install_title = 2131361793;
			
			// aapt resource value: 0x7f0a0010
			public const int common_google_play_services_invalid_account_text = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int common_google_play_services_invalid_account_title = 2131361807;
			
			// aapt resource value: 0x7f0a000e
			public const int common_google_play_services_network_error_text = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int common_google_play_services_network_error_title = 2131361805;
			
			// aapt resource value: 0x7f0a0000
			public const int common_google_play_services_notification_ticker = 2131361792;
			
			// aapt resource value: 0x7f0a0019
			public const int common_google_play_services_restricted_profile_text = 2131361817;
			
			// aapt resource value: 0x7f0a0018
			public const int common_google_play_services_restricted_profile_title = 2131361816;
			
			// aapt resource value: 0x7f0a0017
			public const int common_google_play_services_sign_in_failed_text = 2131361815;
			
			// aapt resource value: 0x7f0a0016
			public const int common_google_play_services_sign_in_failed_title = 2131361814;
			
			// aapt resource value: 0x7f0a001e
			public const int common_google_play_services_unknown_issue = 2131361822;
			
			// aapt resource value: 0x7f0a0012
			public const int common_google_play_services_unsupported_text = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int common_google_play_services_unsupported_title = 2131361809;
			
			// aapt resource value: 0x7f0a0013
			public const int common_google_play_services_update_button = 2131361811;
			
			// aapt resource value: 0x7f0a0009
			public const int common_google_play_services_update_text = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int common_google_play_services_update_title = 2131361800;
			
			// aapt resource value: 0x7f0a000c
			public const int common_google_play_services_updating_text = 2131361804;
			
			// aapt resource value: 0x7f0a000b
			public const int common_google_play_services_updating_title = 2131361803;
			
			// aapt resource value: 0x7f0a000a
			public const int common_google_play_services_wear_update_text = 2131361802;
			
			// aapt resource value: 0x7f0a0014
			public const int common_open_on_phone = 2131361812;
			
			// aapt resource value: 0x7f0a001a
			public const int common_signin_button_text = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int common_signin_button_text_long = 2131361819;
			
			// aapt resource value: 0x7f0a004c
			public const int hello = 2131361868;
			
			// aapt resource value: 0x7f0a001f
			public const int ua_cancel = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int ua_channel_copy_toast = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int ua_channel_notification_ticker = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int ua_connection_error = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int ua_delete = 2131361827;
			
			// aapt resource value: 0x7f0a0048
			public const int ua_emoji_happy = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int ua_emoji_sad = 2131361865;
			
			// aapt resource value: 0x7f0a004a
			public const int ua_emoji_thumbs_down = 2131361866;
			
			// aapt resource value: 0x7f0a004b
			public const int ua_emoji_thumbs_up = 2131361867;
			
			// aapt resource value: 0x7f0a0024
			public const int ua_empty_message_list = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int ua_mark_read = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int ua_mc_failed_to_load = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public const int ua_message_center_title = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int ua_message_not_selected = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int ua_notification_button_accept = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int ua_notification_button_add = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int ua_notification_button_add_to_calendar = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public const int ua_notification_button_book_now = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int ua_notification_button_buy_now = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int ua_notification_button_copy = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int ua_notification_button_decline = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int ua_notification_button_dislike = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int ua_notification_button_download = 2131361841;
			
			// aapt resource value: 0x7f0a0032
			public const int ua_notification_button_follow = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int ua_notification_button_less_like = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public const int ua_notification_button_like = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int ua_notification_button_more_like = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int ua_notification_button_no = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int ua_notification_button_opt_in = 2131361847;
			
			// aapt resource value: 0x7f0a0038
			public const int ua_notification_button_opt_out = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public const int ua_notification_button_rate_now = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int ua_notification_button_remind = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int ua_notification_button_save = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int ua_notification_button_search = 2131361852;
			
			// aapt resource value: 0x7f0a003d
			public const int ua_notification_button_send_info = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public const int ua_notification_button_share = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public const int ua_notification_button_shop_now = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int ua_notification_button_tell_me_more = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public const int ua_notification_button_unfollow = 2131361857;
			
			// aapt resource value: 0x7f0a0042
			public const int ua_notification_button_yes = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public const int ua_ok = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int ua_retry_button = 2131361860;
			
			// aapt resource value: 0x7f0a0045
			public const int ua_select_all = 2131361861;
			
			// aapt resource value: 0x7f0a0046
			public const int ua_select_none = 2131361862;
			
			// aapt resource value: 0x7f0a0047
			public const int ua_share_dialog_title = 2131361863;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Base_CardView = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_ActionButton = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_ActionButtonContainer = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_DismissButton = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_Divider = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_Text = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int Base_Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Base_Widget_UrbanAirship_MessageCenter_Item_Container = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int Base_Widget_UrbanAirship_MessageCenter_Item_Date = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int Base_Widget_UrbanAirship_MessageCenter_Item_Icon = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int Base_Widget_UrbanAirship_MessageCenter_Item_Title = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int CardView_Light = 2131165187;
			
			// aapt resource value: 0x7f07000f
			public const int InAppMessage_Banner = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int InAppMessage_Banner_TextAppearance = 2131165200;
			
			// aapt resource value: 0x7f070022
			public const int LandingPageStyle = 2131165218;
			
			// aapt resource value: 0x7f070011
			public const int MessageCenter = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int MessageCenter_EmptyMessage_TextAppearance = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int MessageCenter_Item_Date_TextAppearance = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int MessageCenter_Item_Title_TextAppearance = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int MessageCenter_MessageNotSelected_TextAppearance = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int Widget_UrbanAirship_InAppMessage_Banner = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int Widget_UrbanAirship_InAppMessage_Banner_ActionButton = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int Widget_UrbanAirship_InAppMessage_Banner_ActionButtonContainer = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int Widget_UrbanAirship_InAppMessage_Banner_Card = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int Widget_UrbanAirship_InAppMessage_Banner_DismissButton = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int Widget_UrbanAirship_InAppMessage_Banner_Divider = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int Widget_UrbanAirship_InAppMessage_Banner_Text = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int Widget_UrbanAirship_MessageCenter_Item_Container = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int Widget_UrbanAirship_MessageCenter_Item_Date = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int Widget_UrbanAirship_MessageCenter_Item_Icon = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int Widget_UrbanAirship_MessageCenter_Item_Title = 2131165217;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int ua_notification_button_overrides = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ua_notification_buttons = 2131034113;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BannerView = new int[]
			{
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 6
			public const int BannerView_bannerActionButtonTextAppearance = 6;
			
			// aapt resource value: 4
			public const int BannerView_bannerDismissButtonDrawable = 4;
			
			// aapt resource value: 0
			public const int BannerView_bannerFontPath = 0;
			
			// aapt resource value: 5
			public const int BannerView_bannerNoDismissButton = 5;
			
			// aapt resource value: 2
			public const int BannerView_bannerPrimaryColor = 2;
			
			// aapt resource value: 3
			public const int BannerView_bannerSecondaryColor = 3;
			
			// aapt resource value: 1
			public const int BannerView_bannerTextAppearance = 1;
			
			public static int[] CardView = new int[]
			{
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			// aapt resource value: 13
			public const int CardView_optCardBackgroundColor = 13;
			
			// aapt resource value: 14
			public const int CardView_optCardCornerRadius = 14;
			
			// aapt resource value: 15
			public const int CardView_optCardElevation = 15;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MessageCenter = new int[]
			{
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 7
			public const int MessageCenter_messageCenterDividerColor = 7;
			
			// aapt resource value: 6
			public const int MessageCenter_messageCenterEmptyMessageText = 6;
			
			// aapt resource value: 5
			public const int MessageCenter_messageCenterEmptyMessageTextAppearance = 5;
			
			// aapt resource value: 0
			public const int MessageCenter_messageCenterItemBackground = 0;
			
			// aapt resource value: 2
			public const int MessageCenter_messageCenterItemDateTextAppearance = 2;
			
			// aapt resource value: 8
			public const int MessageCenter_messageCenterItemIconEnabled = 8;
			
			// aapt resource value: 9
			public const int MessageCenter_messageCenterItemIconPlaceholder = 9;
			
			// aapt resource value: 1
			public const int MessageCenter_messageCenterItemTitleTextAppearance = 1;
			
			// aapt resource value: 4
			public const int MessageCenter_messageNotSelectedText = 4;
			
			// aapt resource value: 3
			public const int MessageCenter_messageNotSelectedTextAppearance = 3;
			
			public static int[] SignInButton = new int[]
			{
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			public static int[] States = new int[]
			{
					2130772005};
			
			// aapt resource value: 0
			public const int States_ua_state_highlighted = 0;
			
			public static int[] TextAppearance = new int[]
			{
					2130772006};
			
			// aapt resource value: 0
			public const int TextAppearance_urbanAirshipFontPath = 0;
			
			public static int[] Theme = new int[]
			{
					2130772007,
					2130772008};
			
			// aapt resource value: 0
			public const int Theme_inAppMessageBannerStyle = 0;
			
			// aapt resource value: 1
			public const int Theme_messageCenterStyle = 1;
			
			public static int[] UAWebView = new int[]
			{
					2130772009};
			
			// aapt resource value: 0
			public const int UAWebView_mixed_content_mode = 0;
			
			public static int[] UrbanAirshipActionButton = new int[]
			{
					16842753,
					16842754};
			
			// aapt resource value: 1
			public const int UrbanAirshipActionButton_android_icon = 1;
			
			// aapt resource value: 0
			public const int UrbanAirshipActionButton_android_label = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
