//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SampleApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string home_title {
            get {
                return ResourceManager.GetString("home_title", resourceCulture);
            }
        }
        
        internal static string settings_title {
            get {
                return ResourceManager.GetString("settings_title", resourceCulture);
            }
        }
        
        internal static string enable_push {
            get {
                return ResourceManager.GetString("enable_push", resourceCulture);
            }
        }
        
        internal static string display_message_center {
            get {
                return ResourceManager.GetString("display_message_center", resourceCulture);
            }
        }
        
        internal static string push_settings_category_title {
            get {
                return ResourceManager.GetString("push_settings_category_title", resourceCulture);
            }
        }
        
        internal static string device_settings_category_title {
            get {
                return ResourceManager.GetString("device_settings_category_title", resourceCulture);
            }
        }
        
        internal static string push_enabled_cell_title {
            get {
                return ResourceManager.GetString("push_enabled_cell_title", resourceCulture);
            }
        }
        
        internal static string channel_id_cell_title {
            get {
                return ResourceManager.GetString("channel_id_cell_title", resourceCulture);
            }
        }
        
        internal static string named_user_cell_title {
            get {
                return ResourceManager.GetString("named_user_cell_title", resourceCulture);
            }
        }
        
        internal static string alert_title {
            get {
                return ResourceManager.GetString("alert_title", resourceCulture);
            }
        }
        
        internal static string alert_copied_channel_id {
            get {
                return ResourceManager.GetString("alert_copied_channel_id", resourceCulture);
            }
        }
        
        internal static string channel_id_cell_placeholder {
            get {
                return ResourceManager.GetString("channel_id_cell_placeholder", resourceCulture);
            }
        }
        
        internal static string alert_named_user_added_successuflully {
            get {
                return ResourceManager.GetString("alert_named_user_added_successuflully", resourceCulture);
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
    }
}
