//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel ID copied to clipboard!.
        /// </summary>
        internal static string alert_copied_channel_id {
            get {
                return ResourceManager.GetString("alert_copied_channel_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named user added successufully.
        /// </summary>
        internal static string alert_named_user_added_successuflully {
            get {
                return ResourceManager.GetString("alert_named_user_added_successuflully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string alert_title {
            get {
                return ResourceManager.GetString("alert_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add your named user.
        /// </summary>
        internal static string channel_id_cell_placeholder {
            get {
                return ResourceManager.GetString("channel_id_cell_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel ID.
        /// </summary>
        internal static string channel_id_cell_title {
            get {
                return ResourceManager.GetString("channel_id_cell_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVICE SETTINGS.
        /// </summary>
        internal static string device_settings_category_title {
            get {
                return ResourceManager.GetString("device_settings_category_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPLAY MESSAGE CENTER.
        /// </summary>
        internal static string display_message_center {
            get {
                return ResourceManager.GetString("display_message_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPLAY PREFERENCE CENTER.
        /// </summary>
        internal static string display_preference_center {
            get {
                return ResourceManager.GetString("display_preference_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENABLE PUSH.
        /// </summary>
        internal static string enable_push {
            get {
                return ResourceManager.GetString("enable_push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string home_title {
            get {
                return ResourceManager.GetString("home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGE CENTER.
        /// </summary>
        internal static string message_center_title {
            get {
                return ResourceManager.GetString("message_center_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named User.
        /// </summary>
        internal static string named_user_cell_title {
            get {
                return ResourceManager.GetString("named_user_cell_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Enabled.
        /// </summary>
        internal static string push_enabled_cell_title {
            get {
                return ResourceManager.GetString("push_enabled_cell_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUSH SETTINGS.
        /// </summary>
        internal static string push_settings_category_title {
            get {
                return ResourceManager.GetString("push_settings_category_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string settings_title {
            get {
                return ResourceManager.GetString("settings_title", resourceCulture);
            }
        }
    }
}
