#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AirshipBindings.NETStandard.Android.Resource", IsApplication=false)]

namespace AirshipBindings.NETStandard.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public static int ua_iam_slide_in_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int ua_iam_slide_in_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int ua_iam_slide_out_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int ua_iam_slide_out_top = 2130968579;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010006
			public static int cardBackgroundColor = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int cardCornerRadius = 2130771975;
			
			// aapt resource value: 0x7f010008
			public static int cardElevation = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int cardMaxElevation = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public static int cardPreventCornerOverlap = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public static int cardUseCompatPadding = 2130771978;
			
			// aapt resource value: 0x7f010002
			public static int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public static int contentPadding = 2130771980;
			
			// aapt resource value: 0x7f010010
			public static int contentPaddingBottom = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public static int contentPaddingLeft = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public static int contentPaddingRight = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public static int contentPaddingTop = 2130771983;
			
			// aapt resource value: 0x7f010018
			public static int font = 2130771992;
			
			// aapt resource value: 0x7f010011
			public static int fontProviderAuthority = 2130771985;
			
			// aapt resource value: 0x7f010014
			public static int fontProviderCerts = 2130771988;
			
			// aapt resource value: 0x7f010015
			public static int fontProviderFetchStrategy = 2130771989;
			
			// aapt resource value: 0x7f010016
			public static int fontProviderFetchTimeout = 2130771990;
			
			// aapt resource value: 0x7f010012
			public static int fontProviderPackage = 2130771986;
			
			// aapt resource value: 0x7f010013
			public static int fontProviderQuery = 2130771987;
			
			// aapt resource value: 0x7f010017
			public static int fontStyle = 2130771991;
			
			// aapt resource value: 0x7f010019
			public static int fontWeight = 2130771993;
			
			// aapt resource value: 0x7f010001
			public static int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010021
			public static int messageCenterDividerColor = 2130772001;
			
			// aapt resource value: 0x7f010020
			public static int messageCenterEmptyMessageText = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public static int messageCenterEmptyMessageTextAppearance = 2130771999;
			
			// aapt resource value: 0x7f01001a
			public static int messageCenterItemBackground = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public static int messageCenterItemDateTextAppearance = 2130771996;
			
			// aapt resource value: 0x7f010022
			public static int messageCenterItemIconEnabled = 2130772002;
			
			// aapt resource value: 0x7f010023
			public static int messageCenterItemIconPlaceholder = 2130772003;
			
			// aapt resource value: 0x7f01001b
			public static int messageCenterItemTitleTextAppearance = 2130771995;
			
			// aapt resource value: 0x7f010026
			public static int messageCenterStyle = 2130772006;
			
			// aapt resource value: 0x7f01001e
			public static int messageNotSelectedText = 2130771998;
			
			// aapt resource value: 0x7f01001d
			public static int messageNotSelectedTextAppearance = 2130771997;
			
			// aapt resource value: 0x7f010027
			public static int mixed_content_mode = 2130772007;
			
			// aapt resource value: 0x7f010005
			public static int scopeUris = 2130771973;
			
			// aapt resource value: 0x7f010024
			public static int ua_state_highlighted = 2130772004;
			
			// aapt resource value: 0x7f010028
			public static int urbanAirshipButtonLayoutResourceId = 2130772008;
			
			// aapt resource value: 0x7f010025
			public static int urbanAirshipFontPath = 2130772005;
			
			// aapt resource value: 0x7f01002c
			public static int urbanAirshipMaxHeight = 2130772012;
			
			// aapt resource value: 0x7f01002b
			public static int urbanAirshipMaxWidth = 2130772011;
			
			// aapt resource value: 0x7f01002a
			public static int urbanAirshipSeparatedSpaceWidth = 2130772010;
			
			// aapt resource value: 0x7f010029
			public static int urbanAirshipStackedSpaceHeight = 2130772009;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0c0000
			public static int abc_action_bar_embed_tabs = 2131492864;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090008
			public static int cardview_dark_background = 2131296264;
			
			// aapt resource value: 0x7f090009
			public static int cardview_light_background = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public static int cardview_shadow_end_color = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public static int cardview_shadow_start_color = 2131296267;
			
			// aapt resource value: 0x7f090013
			public static int common_google_signin_btn_text_dark = 2131296275;
			
			// aapt resource value: 0x7f090000
			public static int common_google_signin_btn_text_dark_default = 2131296256;
			
			// aapt resource value: 0x7f090001
			public static int common_google_signin_btn_text_dark_disabled = 2131296257;
			
			// aapt resource value: 0x7f090002
			public static int common_google_signin_btn_text_dark_focused = 2131296258;
			
			// aapt resource value: 0x7f090003
			public static int common_google_signin_btn_text_dark_pressed = 2131296259;
			
			// aapt resource value: 0x7f090014
			public static int common_google_signin_btn_text_light = 2131296276;
			
			// aapt resource value: 0x7f090004
			public static int common_google_signin_btn_text_light_default = 2131296260;
			
			// aapt resource value: 0x7f090005
			public static int common_google_signin_btn_text_light_disabled = 2131296261;
			
			// aapt resource value: 0x7f090006
			public static int common_google_signin_btn_text_light_focused = 2131296262;
			
			// aapt resource value: 0x7f090007
			public static int common_google_signin_btn_text_light_pressed = 2131296263;
			
			// aapt resource value: 0x7f090015
			public static int common_google_signin_btn_tint = 2131296277;
			
			// aapt resource value: 0x7f09000f
			public static int notification_action_color_filter = 2131296271;
			
			// aapt resource value: 0x7f090010
			public static int notification_icon_bg_color = 2131296272;
			
			// aapt resource value: 0x7f09000c
			public static int notification_material_background_media_default_color = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public static int primary_text_default_material_dark = 2131296269;
			
			// aapt resource value: 0x7f090011
			public static int ripple_material_light = 2131296273;
			
			// aapt resource value: 0x7f09000e
			public static int secondary_text_default_material_dark = 2131296270;
			
			// aapt resource value: 0x7f090012
			public static int secondary_text_default_material_light = 2131296274;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0b0000
			public static int cardview_compat_inset_shadow = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public static int cardview_default_elevation = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public static int cardview_default_radius = 2131427330;
			
			// aapt resource value: 0x7f0b0007
			public static int compat_button_inset_horizontal_material = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public static int compat_button_inset_vertical_material = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public static int compat_button_padding_horizontal_material = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public static int compat_button_padding_vertical_material = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public static int compat_control_corner_material = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public static int notification_action_icon_size = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public static int notification_action_text_size = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public static int notification_big_circle_margin = 2131427342;
			
			// aapt resource value: 0x7f0b0004
			public static int notification_content_margin_start = 2131427332;
			
			// aapt resource value: 0x7f0b000f
			public static int notification_large_icon_height = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public static int notification_large_icon_width = 2131427344;
			
			// aapt resource value: 0x7f0b0005
			public static int notification_main_column_padding_top = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public static int notification_media_narrow_margin = 2131427334;
			
			// aapt resource value: 0x7f0b0011
			public static int notification_right_icon_size = 2131427345;
			
			// aapt resource value: 0x7f0b0003
			public static int notification_right_side_padding_top = 2131427331;
			
			// aapt resource value: 0x7f0b0012
			public static int notification_small_icon_background_padding = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public static int notification_small_icon_size_as_large = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public static int notification_subtext_size = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public static int notification_top_pad = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public static int notification_top_pad_large_text = 2131427350;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int notification_action_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int notification_bg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int notification_bg_low = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int notification_bg_low_normal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int notification_bg_low_pressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int notification_bg_normal = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int notification_bg_normal_pressed = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int notification_icon_background = 2130837532;
			
			// aapt resource value: 0x7f02003a
			public static int notification_template_icon_bg = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public static int notification_template_icon_low_bg = 2130837563;
			
			// aapt resource value: 0x7f02001d
			public static int notification_tile_bg = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int notify_panel_notification_icon_bg = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int ua_iam_banner_pull_background = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int ua_ic_close = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int ua_ic_close_white_18dp = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int ua_ic_image_placeholder = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int ua_ic_notification_button_accept = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int ua_ic_notification_button_add = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int ua_ic_notification_button_book = 2130837541;
			
			// aapt resource value: 0x7f020026
			public static int ua_ic_notification_button_cart = 2130837542;
			
			// aapt resource value: 0x7f020027
			public static int ua_ic_notification_button_copy = 2130837543;
			
			// aapt resource value: 0x7f020028
			public static int ua_ic_notification_button_decline = 2130837544;
			
			// aapt resource value: 0x7f020029
			public static int ua_ic_notification_button_download = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public static int ua_ic_notification_button_event = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public static int ua_ic_notification_button_follow = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public static int ua_ic_notification_button_happy = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public static int ua_ic_notification_button_info = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public static int ua_ic_notification_button_open_browser = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public static int ua_ic_notification_button_remind = 2130837551;
			
			// aapt resource value: 0x7f020030
			public static int ua_ic_notification_button_sad = 2130837552;
			
			// aapt resource value: 0x7f020031
			public static int ua_ic_notification_button_save = 2130837553;
			
			// aapt resource value: 0x7f020032
			public static int ua_ic_notification_button_search = 2130837554;
			
			// aapt resource value: 0x7f020033
			public static int ua_ic_notification_button_send = 2130837555;
			
			// aapt resource value: 0x7f020034
			public static int ua_ic_notification_button_share = 2130837556;
			
			// aapt resource value: 0x7f020035
			public static int ua_ic_notification_button_thumbs_down = 2130837557;
			
			// aapt resource value: 0x7f020036
			public static int ua_ic_notification_button_thumbs_up = 2130837558;
			
			// aapt resource value: 0x7f020037
			public static int ua_ic_notification_button_unfollow = 2130837559;
			
			// aapt resource value: 0x7f020038
			public static int ua_ic_urbanairship_notification = 2130837560;
			
			// aapt resource value: 0x7f020039
			public static int ua_item_mc_background = 2130837561;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d001a
			public static int action0 = 2131558426;
			
			// aapt resource value: 0x7f0d0017
			public static int action_container = 2131558423;
			
			// aapt resource value: 0x7f0d001e
			public static int action_divider = 2131558430;
			
			// aapt resource value: 0x7f0d0018
			public static int action_image = 2131558424;
			
			// aapt resource value: 0x7f0d0019
			public static int action_text = 2131558425;
			
			// aapt resource value: 0x7f0d0028
			public static int actions = 2131558440;
			
			// aapt resource value: 0x7f0d0006
			public static int adjust_height = 2131558406;
			
			// aapt resource value: 0x7f0d0007
			public static int adjust_width = 2131558407;
			
			// aapt resource value: 0x7f0d0014
			public static int always_allow = 2131558420;
			
			// aapt resource value: 0x7f0d000f
			public static int async = 2131558415;
			
			// aapt resource value: 0x7f0d000c
			public static int auto = 2131558412;
			
			// aapt resource value: 0x7f0d0039
			public static int banner = 2131558457;
			
			// aapt resource value: 0x7f0d003b
			public static int banner_content = 2131558459;
			
			// aapt resource value: 0x7f0d003a
			public static int banner_pull = 2131558458;
			
			// aapt resource value: 0x7f0d0010
			public static int blocking = 2131558416;
			
			// aapt resource value: 0x7f0d0040
			public static int body = 2131558464;
			
			// aapt resource value: 0x7f0d003d
			public static int buttons = 2131558461;
			
			// aapt resource value: 0x7f0d001b
			public static int cancel_action = 2131558427;
			
			// aapt resource value: 0x7f0d002b
			public static int channel_capture_title = 2131558443;
			
			// aapt resource value: 0x7f0d002c
			public static int channel_id = 2131558444;
			
			// aapt resource value: 0x7f0d0030
			public static int channel_information = 2131558448;
			
			// aapt resource value: 0x7f0d0049
			public static int checkbox = 2131558473;
			
			// aapt resource value: 0x7f0d0023
			public static int chronometer = 2131558435;
			
			// aapt resource value: 0x7f0d0032
			public static int close_button = 2131558450;
			
			// aapt resource value: 0x7f0d0015
			public static int compatibility_mode = 2131558421;
			
			// aapt resource value: 0x7f0d0034
			public static int container = 2131558452;
			
			// aapt resource value: 0x7f0d0031
			public static int content_holder = 2131558449;
			
			// aapt resource value: 0x7f0d002e
			public static int copy_button = 2131558446;
			
			// aapt resource value: 0x7f0d000d
			public static int dark = 2131558413;
			
			// aapt resource value: 0x7f0d004a
			public static int date = 2131558474;
			
			// aapt resource value: 0x7f0d004d
			public static int delete = 2131558477;
			
			// aapt resource value: 0x7f0d0041
			public static int dismiss = 2131558465;
			
			// aapt resource value: 0x7f0d002a
			public static int end_padder = 2131558442;
			
			// aapt resource value: 0x7f0d0036
			public static int error = 2131558454;
			
			// aapt resource value: 0x7f0d0043
			public static int footer = 2131558467;
			
			// aapt resource value: 0x7f0d0042
			public static int footer_holder = 2131558466;
			
			// aapt resource value: 0x7f0d0011
			public static int forever = 2131558417;
			
			// aapt resource value: 0x7f0d003f
			public static int heading = 2131558463;
			
			// aapt resource value: 0x7f0d0025
			public static int icon = 2131558437;
			
			// aapt resource value: 0x7f0d0029
			public static int icon_group = 2131558441;
			
			// aapt resource value: 0x7f0d0009
			public static int icon_only = 2131558409;
			
			// aapt resource value: 0x7f0d004b
			public static int image = 2131558475;
			
			// aapt resource value: 0x7f0d0024
			public static int info = 2131558436;
			
			// aapt resource value: 0x7f0d0012
			public static int italic = 2131558418;
			
			// aapt resource value: 0x7f0d000e
			public static int light = 2131558414;
			
			// aapt resource value: 0x7f0d0000
			public static int line1 = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public static int line3 = 2131558401;
			
			// aapt resource value: 0x7f0d004c
			public static int mark_read = 2131558476;
			
			// aapt resource value: 0x7f0d003e
			public static int media = 2131558462;
			
			// aapt resource value: 0x7f0d001d
			public static int media_actions = 2131558429;
			
			// aapt resource value: 0x7f0d0035
			public static int message_container = 2131558453;
			
			// aapt resource value: 0x7f0d0033
			public static int message_list_container = 2131558451;
			
			// aapt resource value: 0x7f0d0046
			public static int modal = 2131558470;
			
			// aapt resource value: 0x7f0d0047
			public static int modal_content = 2131558471;
			
			// aapt resource value: 0x7f0d0016
			public static int never_allow = 2131558422;
			
			// aapt resource value: 0x7f0d0008
			public static int none = 2131558408;
			
			// aapt resource value: 0x7f0d0013
			public static int normal = 2131558419;
			
			// aapt resource value: 0x7f0d0027
			public static int notification_background = 2131558439;
			
			// aapt resource value: 0x7f0d0020
			public static int notification_main_column = 2131558432;
			
			// aapt resource value: 0x7f0d001f
			public static int notification_main_column_container = 2131558431;
			
			// aapt resource value: 0x7f0d002f
			public static int open_button = 2131558447;
			
			// aapt resource value: 0x7f0d0045
			public static int progress = 2131558469;
			
			// aapt resource value: 0x7f0d0037
			public static int retry_button = 2131558455;
			
			// aapt resource value: 0x7f0d0026
			public static int right_icon = 2131558438;
			
			// aapt resource value: 0x7f0d0021
			public static int right_side = 2131558433;
			
			// aapt resource value: 0x7f0d004e
			public static int select_all = 2131558478;
			
			// aapt resource value: 0x7f0d002d
			public static int share_button = 2131558445;
			
			// aapt resource value: 0x7f0d000a
			public static int standard = 2131558410;
			
			// aapt resource value: 0x7f0d001c
			public static int status_bar_latest_event_content = 2131558428;
			
			// aapt resource value: 0x7f0d0038
			public static int swipe_container = 2131558456;
			
			// aapt resource value: 0x7f0d0002
			public static int tag_transition_group = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public static int text = 2131558403;
			
			// aapt resource value: 0x7f0d0004
			public static int text2 = 2131558404;
			
			// aapt resource value: 0x7f0d0022
			public static int time = 2131558434;
			
			// aapt resource value: 0x7f0d0005
			public static int title = 2131558405;
			
			// aapt resource value: 0x7f0d003c
			public static int ua_iam_banner_content_left_image = 2131558460;
			
			// aapt resource value: 0x7f0d0048
			public static int ua_iam_modal_header_body_media = 2131558472;
			
			// aapt resource value: 0x7f0d0044
			public static int web_view = 2131558468;
			
			// aapt resource value: 0x7f0d000b
			public static int wide = 2131558411;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080001
			public static int cancel_button_image_alpha = 2131230721;
			
			// aapt resource value: 0x7f080000
			public static int google_play_services_version = 2131230720;
			
			// aapt resource value: 0x7f080002
			public static int status_bar_notification_info_maxnum = 2131230722;
			
			// aapt resource value: 0x7f080003
			public static int ua_iam_animation_duration = 2131230723;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int notification_action = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int notification_action_tombstone = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int notification_media_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int notification_media_cancel_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int notification_template_big_media = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int notification_template_big_media_custom = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int notification_template_big_media_narrow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int notification_template_big_media_narrow_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int notification_template_custom_big = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int notification_template_icon_group = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int notification_template_lines_media = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int notification_template_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int notification_template_media_custom = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int notification_template_part_chronometer = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int notification_template_part_time = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int ua_activity_channel_capture = 2130903055;
			
			// aapt resource value: 0x7f030010
			public static int ua_activity_landing_page = 2130903056;
			
			// aapt resource value: 0x7f030011
			public static int ua_fragment_mc = 2130903057;
			
			// aapt resource value: 0x7f030012
			public static int ua_fragment_message = 2130903058;
			
			// aapt resource value: 0x7f030013
			public static int ua_fragment_message_list = 2130903059;
			
			// aapt resource value: 0x7f030014
			public static int ua_fragment_no_message_selected = 2130903060;
			
			// aapt resource value: 0x7f030015
			public static int ua_iam_banner_bottom = 2130903061;
			
			// aapt resource value: 0x7f030016
			public static int ua_iam_banner_button = 2130903062;
			
			// aapt resource value: 0x7f030017
			public static int ua_iam_banner_content_left_media = 2130903063;
			
			// aapt resource value: 0x7f030018
			public static int ua_iam_banner_content_right_media = 2130903064;
			
			// aapt resource value: 0x7f030019
			public static int ua_iam_banner_top = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public static int ua_iam_fullscreen_button = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public static int ua_iam_fullscreen_header_body_media = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public static int ua_iam_fullscreen_header_media_body = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public static int ua_iam_fullscreen_media_header_body = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public static int ua_iam_html = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public static int ua_iam_modal = 2130903071;
			
			// aapt resource value: 0x7f030020
			public static int ua_iam_modal_button = 2130903072;
			
			// aapt resource value: 0x7f030021
			public static int ua_iam_modal_header_body_media = 2130903073;
			
			// aapt resource value: 0x7f030022
			public static int ua_iam_modal_header_media_body = 2130903074;
			
			// aapt resource value: 0x7f030023
			public static int ua_iam_modal_media_header_body = 2130903075;
			
			// aapt resource value: 0x7f030024
			public static int ua_item_mc = 2130903076;
			
			// aapt resource value: 0x7f030025
			public static int ua_item_mc_content = 2130903077;
			
			// aapt resource value: 0x7f030026
			public static int ua_item_mc_icon_content = 2130903078;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0f0000
			public static int ua_mc_action_mode = 2131689472;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f0e0000
			public static int ua_selected_count = 2131623936;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public static int ua_native_bridge = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public static int common_google_play_services_enable_button = 2131165186;
			
			// aapt resource value: 0x7f070003
			public static int common_google_play_services_enable_text = 2131165187;
			
			// aapt resource value: 0x7f070004
			public static int common_google_play_services_enable_title = 2131165188;
			
			// aapt resource value: 0x7f070005
			public static int common_google_play_services_install_button = 2131165189;
			
			// aapt resource value: 0x7f070006
			public static int common_google_play_services_install_text = 2131165190;
			
			// aapt resource value: 0x7f070007
			public static int common_google_play_services_install_title = 2131165191;
			
			// aapt resource value: 0x7f070008
			public static int common_google_play_services_notification_ticker = 2131165192;
			
			// aapt resource value: 0x7f070001
			public static int common_google_play_services_unknown_issue = 2131165185;
			
			// aapt resource value: 0x7f070009
			public static int common_google_play_services_unsupported_text = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public static int common_google_play_services_update_button = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public static int common_google_play_services_update_text = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public static int common_google_play_services_update_title = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public static int common_google_play_services_updating_text = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public static int common_google_play_services_wear_update_text = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public static int common_open_on_phone = 2131165199;
			
			// aapt resource value: 0x7f070010
			public static int common_signin_button_text = 2131165200;
			
			// aapt resource value: 0x7f070011
			public static int common_signin_button_text_long = 2131165201;
			
			// aapt resource value: 0x7f070000
			public static int gcm_fallback_notification_channel_label = 2131165184;
			
			// aapt resource value: 0x7f07004c
			public static int library_name = 2131165260;
			
			// aapt resource value: 0x7f070012
			public static int status_bar_notification_info_overflow = 2131165202;
			
			// aapt resource value: 0x7f070013
			public static int ua_cancel = 2131165203;
			
			// aapt resource value: 0x7f070014
			public static int ua_channel_copy_toast = 2131165204;
			
			// aapt resource value: 0x7f070015
			public static int ua_channel_id = 2131165205;
			
			// aapt resource value: 0x7f070016
			public static int ua_channel_notification_ticker = 2131165206;
			
			// aapt resource value: 0x7f070017
			public static int ua_connection_error = 2131165207;
			
			// aapt resource value: 0x7f070018
			public static int ua_content_error = 2131165208;
			
			// aapt resource value: 0x7f070019
			public static int ua_default_channel_description = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public static int ua_default_channel_name = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public static int ua_delete = 2131165211;
			
			// aapt resource value: 0x7f070048
			public static int ua_emoji_happy = 2131165256;
			
			// aapt resource value: 0x7f070049
			public static int ua_emoji_sad = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public static int ua_emoji_thumbs_down = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public static int ua_emoji_thumbs_up = 2131165259;
			
			// aapt resource value: 0x7f07001c
			public static int ua_empty_message_list = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public static int ua_mark_read = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public static int ua_mc_failed_to_load = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public static int ua_mc_no_longer_available = 2131165215;
			
			// aapt resource value: 0x7f070020
			public static int ua_message_center_title = 2131165216;
			
			// aapt resource value: 0x7f070021
			public static int ua_message_not_selected = 2131165217;
			
			// aapt resource value: 0x7f070022
			public static int ua_notification_button_accept = 2131165218;
			
			// aapt resource value: 0x7f070023
			public static int ua_notification_button_add = 2131165219;
			
			// aapt resource value: 0x7f070024
			public static int ua_notification_button_add_to_calendar = 2131165220;
			
			// aapt resource value: 0x7f070025
			public static int ua_notification_button_book_now = 2131165221;
			
			// aapt resource value: 0x7f070026
			public static int ua_notification_button_buy_now = 2131165222;
			
			// aapt resource value: 0x7f070027
			public static int ua_notification_button_copy = 2131165223;
			
			// aapt resource value: 0x7f070028
			public static int ua_notification_button_decline = 2131165224;
			
			// aapt resource value: 0x7f070029
			public static int ua_notification_button_dislike = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public static int ua_notification_button_download = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public static int ua_notification_button_follow = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public static int ua_notification_button_less_like = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public static int ua_notification_button_like = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public static int ua_notification_button_more_like = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public static int ua_notification_button_no = 2131165231;
			
			// aapt resource value: 0x7f070030
			public static int ua_notification_button_opt_in = 2131165232;
			
			// aapt resource value: 0x7f070031
			public static int ua_notification_button_opt_out = 2131165233;
			
			// aapt resource value: 0x7f070032
			public static int ua_notification_button_rate_now = 2131165234;
			
			// aapt resource value: 0x7f070033
			public static int ua_notification_button_remind = 2131165235;
			
			// aapt resource value: 0x7f070034
			public static int ua_notification_button_save = 2131165236;
			
			// aapt resource value: 0x7f070035
			public static int ua_notification_button_search = 2131165237;
			
			// aapt resource value: 0x7f070036
			public static int ua_notification_button_send_info = 2131165238;
			
			// aapt resource value: 0x7f070037
			public static int ua_notification_button_share = 2131165239;
			
			// aapt resource value: 0x7f070038
			public static int ua_notification_button_shop_now = 2131165240;
			
			// aapt resource value: 0x7f070039
			public static int ua_notification_button_tell_me_more = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public static int ua_notification_button_unfollow = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public static int ua_notification_button_yes = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public static int ua_ok = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public static int ua_open = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public static int ua_rate_app_action_default_body = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public static int ua_rate_app_action_default_rate_negative_button = 2131165247;
			
			// aapt resource value: 0x7f070040
			public static int ua_rate_app_action_default_rate_positive_button = 2131165248;
			
			// aapt resource value: 0x7f070041
			public static int ua_rate_app_action_default_title = 2131165249;
			
			// aapt resource value: 0x7f070042
			public static int ua_rate_app_action_generic_display_name = 2131165250;
			
			// aapt resource value: 0x7f070043
			public static int ua_refresh = 2131165251;
			
			// aapt resource value: 0x7f070044
			public static int ua_retry_button = 2131165252;
			
			// aapt resource value: 0x7f070045
			public static int ua_select_all = 2131165253;
			
			// aapt resource value: 0x7f070046
			public static int ua_select_none = 2131165254;
			
			// aapt resource value: 0x7f070047
			public static int ua_share_dialog_title = 2131165255;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0001
			public static int Base_CardView = 2131361793;
			
			// aapt resource value: 0x7f0a0010
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Container = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Date = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Icon = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Title = 2131361812;
			
			// aapt resource value: 0x7f0a0000
			public static int CardView = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public static int CardView_Dark = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public static int CardView_Light = 2131361795;
			
			// aapt resource value: 0x7f0a0015
			public static int MessageCenter = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public static int MessageCenter_EmptyMessage_TextAppearance = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public static int MessageCenter_Item_Date_TextAppearance = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public static int MessageCenter_Item_Title_TextAppearance = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public static int MessageCenter_MessageNotSelected_TextAppearance = 2131361817;
			
			// aapt resource value: 0x7f0a0009
			public static int TextAppearance_Compat_Notification = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public static int TextAppearance_Compat_Notification_Info = 2131361802;
			
			// aapt resource value: 0x7f0a0004
			public static int TextAppearance_Compat_Notification_Info_Media = 2131361796;
			
			// aapt resource value: 0x7f0a000f
			public static int TextAppearance_Compat_Notification_Line2 = 2131361807;
			
			// aapt resource value: 0x7f0a0008
			public static int TextAppearance_Compat_Notification_Line2_Media = 2131361800;
			
			// aapt resource value: 0x7f0a0005
			public static int TextAppearance_Compat_Notification_Media = 2131361797;
			
			// aapt resource value: 0x7f0a000b
			public static int TextAppearance_Compat_Notification_Time = 2131361803;
			
			// aapt resource value: 0x7f0a0006
			public static int TextAppearance_Compat_Notification_Time_Media = 2131361798;
			
			// aapt resource value: 0x7f0a000c
			public static int TextAppearance_Compat_Notification_Title = 2131361804;
			
			// aapt resource value: 0x7f0a0007
			public static int TextAppearance_Compat_Notification_Title_Media = 2131361799;
			
			// aapt resource value: 0x7f0a001a
			public static int UrbanAirship = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public static int UrbanAirship_InAppBanner = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public static int UrbanAirship_InAppBanner_Body = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public static int UrbanAirship_InAppBanner_Button = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public static int UrbanAirship_InAppBanner_ButtonLayout = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public static int UrbanAirship_InAppBanner_Heading = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public static int UrbanAirship_InAppBanner_Layout = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public static int UrbanAirship_InAppBanner_Layout_Bottom = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public static int UrbanAirship_InAppBanner_Layout_Top = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public static int UrbanAirship_InAppBanner_MediaView = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public static int UrbanAirship_InAppBanner_MediaView_Left = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public static int UrbanAirship_InAppBanner_MediaView_Right = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public static int UrbanAirship_InAppBanner_Pull = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public static int UrbanAirship_InAppBanner_Pull_Bottom = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public static int UrbanAirship_InAppBanner_Pull_Top = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public static int UrbanAirship_InAppFullscreen = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public static int UrbanAirship_InAppFullscreen_Body = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public static int UrbanAirship_InAppFullscreen_Button = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public static int UrbanAirship_InAppFullscreen_ButtonLayout = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public static int UrbanAirship_InAppFullscreen_DismissButton = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public static int UrbanAirship_InAppFullscreen_Footer = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public static int UrbanAirship_InAppFullscreen_Heading = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public static int UrbanAirship_InAppFullscreen_Layout = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public static int UrbanAirship_InAppFullscreen_MediaView = 2131361841;
			
			// aapt resource value: 0x7f0a0032
			public static int UrbanAirship_InAppHtml = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public static int UrbanAirship_InAppHtml_DismissButton = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public static int UrbanAirship_InAppHtml_Layout = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public static int UrbanAirship_InAppHtml_Progress = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public static int UrbanAirship_InAppHtml_WebView = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public static int UrbanAirship_InAppModal = 2131361847;
			
			// aapt resource value: 0x7f0a0038
			public static int UrbanAirship_InAppModal_Activity = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public static int UrbanAirship_InAppModal_Body = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public static int UrbanAirship_InAppModal_Button = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public static int UrbanAirship_InAppModal_ButtonLayout = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public static int UrbanAirship_InAppModal_Content = 2131361852;
			
			// aapt resource value: 0x7f0a003d
			public static int UrbanAirship_InAppModal_DismissButton = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public static int UrbanAirship_InAppModal_Footer = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public static int UrbanAirship_InAppModal_Heading = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public static int UrbanAirship_InAppModal_Layout = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public static int UrbanAirship_InAppModal_MediaView = 2131361857;
			
			// aapt resource value: 0x7f0a0042
			public static int UrbanAirship_InAppModal_ScrollView = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public static int UrbanAirship_LandingPageActivity = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public static int UrbanAirship_RateAppActivity = 2131361860;
			
			// aapt resource value: 0x7f0a000d
			public static int Widget_Compat_NotificationActionContainer = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public static int Widget_Compat_NotificationActionText = 2131361806;
			
			// aapt resource value: 0x7f0a0045
			public static int Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131361861;
			
			// aapt resource value: 0x7f0a0046
			public static int Widget_UrbanAirship_MessageCenter_Item_Container = 2131361862;
			
			// aapt resource value: 0x7f0a0047
			public static int Widget_UrbanAirship_MessageCenter_Item_Date = 2131361863;
			
			// aapt resource value: 0x7f0a0048
			public static int Widget_UrbanAirship_MessageCenter_Item_Icon = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public static int Widget_UrbanAirship_MessageCenter_Item_Title = 2131361865;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public static int ua_default_actions = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int ua_notification_button_overrides = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int ua_notification_buttons = 2131034114;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public static int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public static int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public static int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public static int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public static int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public static int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public static int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public static int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public static int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public static int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public static int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public static int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public static int CardView_contentPaddingTop = 11;
			
			public static int[] FontFamily = new int[] {
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public static int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public static int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public static int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public static int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public static int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public static int FontFamilyFont_fontWeight = 5;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public static int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public static int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MessageCenter = new int[] {
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003};
			
			// aapt resource value: 7
			public static int MessageCenter_messageCenterDividerColor = 7;
			
			// aapt resource value: 6
			public static int MessageCenter_messageCenterEmptyMessageText = 6;
			
			// aapt resource value: 5
			public static int MessageCenter_messageCenterEmptyMessageTextAppearance = 5;
			
			// aapt resource value: 0
			public static int MessageCenter_messageCenterItemBackground = 0;
			
			// aapt resource value: 2
			public static int MessageCenter_messageCenterItemDateTextAppearance = 2;
			
			// aapt resource value: 8
			public static int MessageCenter_messageCenterItemIconEnabled = 8;
			
			// aapt resource value: 9
			public static int MessageCenter_messageCenterItemIconPlaceholder = 9;
			
			// aapt resource value: 1
			public static int MessageCenter_messageCenterItemTitleTextAppearance = 1;
			
			// aapt resource value: 4
			public static int MessageCenter_messageNotSelectedText = 4;
			
			// aapt resource value: 3
			public static int MessageCenter_messageNotSelectedTextAppearance = 3;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public static int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public static int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public static int SignInButton_scopeUris = 2;
			
			public static int[] States = new int[] {
					2130772004};
			
			// aapt resource value: 0
			public static int States_ua_state_highlighted = 0;
			
			public static int[] TextAppearance = new int[] {
					2130772005};
			
			// aapt resource value: 0
			public static int TextAppearance_urbanAirshipFontPath = 0;
			
			public static int[] Theme = new int[] {
					2130772006};
			
			// aapt resource value: 0
			public static int Theme_messageCenterStyle = 0;
			
			public static int[] UAWebView = new int[] {
					2130772007};
			
			// aapt resource value: 0
			public static int UAWebView_mixed_content_mode = 0;
			
			public static int[] UrbanAirshipActionButton = new int[] {
					16842753,
					16842754};
			
			// aapt resource value: 1
			public static int UrbanAirshipActionButton_android_icon = 1;
			
			// aapt resource value: 0
			public static int UrbanAirshipActionButton_android_label = 0;
			
			public static int[] UrbanAirshipInAppButtonLayout = new int[] {
					2130772008,
					2130772009,
					2130772010};
			
			// aapt resource value: 0
			public static int UrbanAirshipInAppButtonLayout_urbanAirshipButtonLayoutResourceId = 0;
			
			// aapt resource value: 2
			public static int UrbanAirshipInAppButtonLayout_urbanAirshipSeparatedSpaceWidth = 2;
			
			// aapt resource value: 1
			public static int UrbanAirshipInAppButtonLayout_urbanAirshipStackedSpaceHeight = 1;
			
			public static int[] UrbanAirshipLayout = new int[] {
					2130772011,
					2130772012};
			
			// aapt resource value: 1
			public static int UrbanAirshipLayout_urbanAirshipMaxHeight = 1;
			
			// aapt resource value: 0
			public static int UrbanAirshipLayout_urbanAirshipMaxWidth = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
