#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AirshipBindings.NETStandard.Resource", IsApplication=false)]

namespace AirshipBindings.NETStandard
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public static int ua_iam_fade_in = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int ua_iam_fade_out = 2130771969;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public static int ua_iam_slide_in_bottom = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int ua_iam_slide_in_top = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int ua_iam_slide_out_bottom = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int ua_iam_slide_out_top = 2130837507;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public static int messageCenterDividerColor = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int messageCenterEmptyMessageText = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int messageCenterEmptyMessageTextAppearance = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int messageCenterItemBackground = 2130903043;
			
			// aapt resource value: 0x7F030004
			public static int messageCenterItemDateTextAppearance = 2130903044;
			
			// aapt resource value: 0x7F030005
			public static int messageCenterItemIconEnabled = 2130903045;
			
			// aapt resource value: 0x7F030006
			public static int messageCenterItemIconPlaceholder = 2130903046;
			
			// aapt resource value: 0x7F030007
			public static int messageCenterItemTitleTextAppearance = 2130903047;
			
			// aapt resource value: 0x7F030008
			public static int messageCenterStyle = 2130903048;
			
			// aapt resource value: 0x7F030009
			public static int messageNotSelectedText = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public static int messageNotSelectedTextAppearance = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public static int mixed_content_mode = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public static int ua_state_highlighted = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public static int urbanAirshipButtonLayoutResourceId = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public static int urbanAirshipMaxHeight = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public static int urbanAirshipMaxWidth = 2130903055;
			
			// aapt resource value: 0x7F030010
			public static int urbanAirshipSeparatedSpaceWidth = 2130903056;
			
			// aapt resource value: 0x7F030011
			public static int urbanAirshipStackedSpaceHeight = 2130903057;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F040000
			public static int ua_iam_html_allow_fullscreen_display = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int ua_iam_modal_allow_fullscreen_display = 2130968577;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public static int ua_iam_banner_pull_background = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int ua_iam_dismiss_background = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int ua_ic_close = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int ua_ic_close_white = 2131034115;
			
			// aapt resource value: 0x7F050004
			public static int ua_ic_image_placeholder = 2131034116;
			
			// aapt resource value: 0x7F050005
			public static int ua_ic_notification_button_accept = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int ua_ic_notification_button_add = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int ua_ic_notification_button_book = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int ua_ic_notification_button_cart = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int ua_ic_notification_button_copy = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int ua_ic_notification_button_decline = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int ua_ic_notification_button_download = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public static int ua_ic_notification_button_event = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public static int ua_ic_notification_button_follow = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public static int ua_ic_notification_button_happy = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public static int ua_ic_notification_button_info = 2131034127;
			
			// aapt resource value: 0x7F050010
			public static int ua_ic_notification_button_open_browser = 2131034128;
			
			// aapt resource value: 0x7F050011
			public static int ua_ic_notification_button_remind = 2131034129;
			
			// aapt resource value: 0x7F050012
			public static int ua_ic_notification_button_sad = 2131034130;
			
			// aapt resource value: 0x7F050013
			public static int ua_ic_notification_button_save = 2131034131;
			
			// aapt resource value: 0x7F050014
			public static int ua_ic_notification_button_search = 2131034132;
			
			// aapt resource value: 0x7F050015
			public static int ua_ic_notification_button_send = 2131034133;
			
			// aapt resource value: 0x7F050016
			public static int ua_ic_notification_button_share = 2131034134;
			
			// aapt resource value: 0x7F050017
			public static int ua_ic_notification_button_thumbs_down = 2131034135;
			
			// aapt resource value: 0x7F050018
			public static int ua_ic_notification_button_thumbs_up = 2131034136;
			
			// aapt resource value: 0x7F050019
			public static int ua_ic_notification_button_unfollow = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public static int ua_ic_urbanairship_notification = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public static int ua_item_mc_background = 2131034139;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public static int always_allow = 2131099648;
			
			// aapt resource value: 0x7F060001
			public static int banner = 2131099649;
			
			// aapt resource value: 0x7F060002
			public static int banner_content = 2131099650;
			
			// aapt resource value: 0x7F060003
			public static int banner_pull = 2131099651;
			
			// aapt resource value: 0x7F060004
			public static int body = 2131099652;
			
			// aapt resource value: 0x7F060005
			public static int buttons = 2131099653;
			
			// aapt resource value: 0x7F060006
			public static int channel_capture_title = 2131099654;
			
			// aapt resource value: 0x7F060007
			public static int channel_id = 2131099655;
			
			// aapt resource value: 0x7F060008
			public static int channel_information = 2131099656;
			
			// aapt resource value: 0x7F060009
			public static int checkbox = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public static int compatibility_mode = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public static int container = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public static int content_holder = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public static int copy_button = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public static int date = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public static int delete = 2131099663;
			
			// aapt resource value: 0x7F060010
			public static int dismiss = 2131099664;
			
			// aapt resource value: 0x7F060011
			public static int error = 2131099665;
			
			// aapt resource value: 0x7F060012
			public static int error_message = 2131099666;
			
			// aapt resource value: 0x7F060013
			public static int footer = 2131099667;
			
			// aapt resource value: 0x7F060014
			public static int footer_holder = 2131099668;
			
			// aapt resource value: 0x7F060015
			public static int heading = 2131099669;
			
			// aapt resource value: 0x7F060016
			public static int image = 2131099670;
			
			// aapt resource value: 0x7F060017
			public static int mark_read = 2131099671;
			
			// aapt resource value: 0x7F060018
			public static int media = 2131099672;
			
			// aapt resource value: 0x7F060019
			public static int message_container = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public static int message_list_container = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public static int modal = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public static int modal_content = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public static int never_allow = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public static int open_button = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public static int progress = 2131099679;
			
			// aapt resource value: 0x7F060020
			public static int retry_button = 2131099680;
			
			// aapt resource value: 0x7F060021
			public static int select_all = 2131099681;
			
			// aapt resource value: 0x7F060022
			public static int share_button = 2131099682;
			
			// aapt resource value: 0x7F060023
			public static int swipe_container = 2131099683;
			
			// aapt resource value: 0x7F060024
			public static int title = 2131099684;
			
			// aapt resource value: 0x7F060025
			public static int ua_iam_banner_content_left_image = 2131099685;
			
			// aapt resource value: 0x7F060026
			public static int ua_iam_modal_header_body_media = 2131099686;
			
			// aapt resource value: 0x7F060027
			public static int web_view = 2131099687;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public static int ua_iam_banner_animation_duration = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public static int ua_activity_channel_capture = 2131230720;
			
			// aapt resource value: 0x7F080001
			public static int ua_fragment_mc = 2131230721;
			
			// aapt resource value: 0x7F080002
			public static int ua_fragment_message = 2131230722;
			
			// aapt resource value: 0x7F080003
			public static int ua_fragment_message_list = 2131230723;
			
			// aapt resource value: 0x7F080004
			public static int ua_fragment_no_message_selected = 2131230724;
			
			// aapt resource value: 0x7F080005
			public static int ua_iam_banner_bottom = 2131230725;
			
			// aapt resource value: 0x7F080006
			public static int ua_iam_banner_button = 2131230726;
			
			// aapt resource value: 0x7F080007
			public static int ua_iam_banner_content_left_media = 2131230727;
			
			// aapt resource value: 0x7F080008
			public static int ua_iam_banner_content_right_media = 2131230728;
			
			// aapt resource value: 0x7F080009
			public static int ua_iam_banner_top = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public static int ua_iam_fullscreen_button = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public static int ua_iam_fullscreen_header_body_media = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public static int ua_iam_fullscreen_header_media_body = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public static int ua_iam_fullscreen_media_header_body = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public static int ua_iam_html = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public static int ua_iam_html_fullscreen = 2131230735;
			
			// aapt resource value: 0x7F080010
			public static int ua_iam_modal = 2131230736;
			
			// aapt resource value: 0x7F080011
			public static int ua_iam_modal_button = 2131230737;
			
			// aapt resource value: 0x7F080012
			public static int ua_iam_modal_fullscreen = 2131230738;
			
			// aapt resource value: 0x7F080013
			public static int ua_iam_modal_header_body_media = 2131230739;
			
			// aapt resource value: 0x7F080014
			public static int ua_iam_modal_header_media_body = 2131230740;
			
			// aapt resource value: 0x7F080015
			public static int ua_iam_modal_media_header_body = 2131230741;
			
			// aapt resource value: 0x7F080016
			public static int ua_item_mc = 2131230742;
			
			// aapt resource value: 0x7F080017
			public static int ua_item_mc_content = 2131230743;
			
			// aapt resource value: 0x7F080018
			public static int ua_item_mc_icon_content = 2131230744;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F090000
			public static int ua_mc_action_mode = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F0B0000
			public static int ua_blank_favicon = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public static int ua_native_bridge = 2131427329;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7F0A0000
			public static int ua_selected_count = 2131361792;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0C0000
			public static int library_name = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public static int ua_cancel = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public static int ua_channel_copy_toast = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public static int ua_channel_id = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public static int ua_channel_notification_ticker = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public static int ua_connection_error = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public static int ua_content_error = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public static int ua_default_channel_description = 2131492871;
			
			// aapt resource value: 0x7F0C0008
			public static int ua_default_channel_name = 2131492872;
			
			// aapt resource value: 0x7F0C0009
			public static int ua_delete = 2131492873;
			
			// aapt resource value: 0x7F0C000A
			public static int ua_emoji_happy = 2131492874;
			
			// aapt resource value: 0x7F0C000B
			public static int ua_emoji_sad = 2131492875;
			
			// aapt resource value: 0x7F0C000C
			public static int ua_emoji_thumbs_down = 2131492876;
			
			// aapt resource value: 0x7F0C000D
			public static int ua_emoji_thumbs_up = 2131492877;
			
			// aapt resource value: 0x7F0C000E
			public static int ua_empty_message_list = 2131492878;
			
			// aapt resource value: 0x7F0C000F
			public static int ua_low_priority_channel_description = 2131492879;
			
			// aapt resource value: 0x7F0C0010
			public static int ua_low_priority_channel_id = 2131492880;
			
			// aapt resource value: 0x7F0C0011
			public static int ua_low_priority_channel_name = 2131492881;
			
			// aapt resource value: 0x7F0C0012
			public static int ua_mark_read = 2131492882;
			
			// aapt resource value: 0x7F0C0013
			public static int ua_mc_failed_to_load = 2131492883;
			
			// aapt resource value: 0x7F0C0014
			public static int ua_mc_no_longer_available = 2131492884;
			
			// aapt resource value: 0x7F0C0015
			public static int ua_message_center_title = 2131492885;
			
			// aapt resource value: 0x7F0C0016
			public static int ua_message_not_selected = 2131492886;
			
			// aapt resource value: 0x7F0C0017
			public static int ua_min_priority_channel_description = 2131492887;
			
			// aapt resource value: 0x7F0C0018
			public static int ua_min_priority_channel_id = 2131492888;
			
			// aapt resource value: 0x7F0C0019
			public static int ua_min_priority_channel_name = 2131492889;
			
			// aapt resource value: 0x7F0C001A
			public static int ua_news_channel_description = 2131492890;
			
			// aapt resource value: 0x7F0C001B
			public static int ua_news_channel_id = 2131492891;
			
			// aapt resource value: 0x7F0C001C
			public static int ua_news_channel_name = 2131492892;
			
			// aapt resource value: 0x7F0C001D
			public static int ua_notification_button_accept = 2131492893;
			
			// aapt resource value: 0x7F0C001E
			public static int ua_notification_button_add = 2131492894;
			
			// aapt resource value: 0x7F0C001F
			public static int ua_notification_button_add_to_calendar = 2131492895;
			
			// aapt resource value: 0x7F0C0020
			public static int ua_notification_button_book_now = 2131492896;
			
			// aapt resource value: 0x7F0C0021
			public static int ua_notification_button_buy_now = 2131492897;
			
			// aapt resource value: 0x7F0C0022
			public static int ua_notification_button_copy = 2131492898;
			
			// aapt resource value: 0x7F0C0023
			public static int ua_notification_button_decline = 2131492899;
			
			// aapt resource value: 0x7F0C0024
			public static int ua_notification_button_dislike = 2131492900;
			
			// aapt resource value: 0x7F0C0025
			public static int ua_notification_button_download = 2131492901;
			
			// aapt resource value: 0x7F0C0026
			public static int ua_notification_button_follow = 2131492902;
			
			// aapt resource value: 0x7F0C0027
			public static int ua_notification_button_less_like = 2131492903;
			
			// aapt resource value: 0x7F0C0028
			public static int ua_notification_button_like = 2131492904;
			
			// aapt resource value: 0x7F0C0029
			public static int ua_notification_button_more_like = 2131492905;
			
			// aapt resource value: 0x7F0C002A
			public static int ua_notification_button_no = 2131492906;
			
			// aapt resource value: 0x7F0C002B
			public static int ua_notification_button_opt_in = 2131492907;
			
			// aapt resource value: 0x7F0C002C
			public static int ua_notification_button_opt_out = 2131492908;
			
			// aapt resource value: 0x7F0C002D
			public static int ua_notification_button_rate_now = 2131492909;
			
			// aapt resource value: 0x7F0C002E
			public static int ua_notification_button_remind = 2131492910;
			
			// aapt resource value: 0x7F0C002F
			public static int ua_notification_button_save = 2131492911;
			
			// aapt resource value: 0x7F0C0030
			public static int ua_notification_button_search = 2131492912;
			
			// aapt resource value: 0x7F0C0031
			public static int ua_notification_button_send_info = 2131492913;
			
			// aapt resource value: 0x7F0C0032
			public static int ua_notification_button_share = 2131492914;
			
			// aapt resource value: 0x7F0C0033
			public static int ua_notification_button_shop_now = 2131492915;
			
			// aapt resource value: 0x7F0C0034
			public static int ua_notification_button_tell_me_more = 2131492916;
			
			// aapt resource value: 0x7F0C0035
			public static int ua_notification_button_unfollow = 2131492917;
			
			// aapt resource value: 0x7F0C0036
			public static int ua_notification_button_yes = 2131492918;
			
			// aapt resource value: 0x7F0C0037
			public static int ua_ok = 2131492919;
			
			// aapt resource value: 0x7F0C0038
			public static int ua_open = 2131492920;
			
			// aapt resource value: 0x7F0C0039
			public static int ua_rate_app_action_default_body = 2131492921;
			
			// aapt resource value: 0x7F0C003A
			public static int ua_rate_app_action_default_rate_negative_button = 2131492922;
			
			// aapt resource value: 0x7F0C003B
			public static int ua_rate_app_action_default_rate_positive_button = 2131492923;
			
			// aapt resource value: 0x7F0C003C
			public static int ua_rate_app_action_default_title = 2131492924;
			
			// aapt resource value: 0x7F0C003D
			public static int ua_rate_app_action_generic_display_name = 2131492925;
			
			// aapt resource value: 0x7F0C003E
			public static int ua_refresh = 2131492926;
			
			// aapt resource value: 0x7F0C003F
			public static int ua_retry_button = 2131492927;
			
			// aapt resource value: 0x7F0C0040
			public static int ua_select_all = 2131492928;
			
			// aapt resource value: 0x7F0C0041
			public static int ua_select_none = 2131492929;
			
			// aapt resource value: 0x7F0C0042
			public static int ua_service_channel_description = 2131492930;
			
			// aapt resource value: 0x7F0C0043
			public static int ua_service_channel_id = 2131492931;
			
			// aapt resource value: 0x7F0C0044
			public static int ua_service_channel_name = 2131492932;
			
			// aapt resource value: 0x7F0C0045
			public static int ua_share_dialog_title = 2131492933;
			
			// aapt resource value: 0x7F0C0046
			public static int ua_urgent_channel_description = 2131492934;
			
			// aapt resource value: 0x7F0C0047
			public static int ua_urgent_channel_id = 2131492935;
			
			// aapt resource value: 0x7F0C0048
			public static int ua_urgent_channel_name = 2131492936;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0D0000
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131558400;
			
			// aapt resource value: 0x7F0D0001
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Container = 2131558401;
			
			// aapt resource value: 0x7F0D0002
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Date = 2131558402;
			
			// aapt resource value: 0x7F0D0003
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Icon = 2131558403;
			
			// aapt resource value: 0x7F0D0004
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Title = 2131558404;
			
			// aapt resource value: 0x7F0D0005
			public static int MessageCenter = 2131558405;
			
			// aapt resource value: 0x7F0D0006
			public static int MessageCenter_EmptyMessage_TextAppearance = 2131558406;
			
			// aapt resource value: 0x7F0D0007
			public static int MessageCenter_Item_Date_TextAppearance = 2131558407;
			
			// aapt resource value: 0x7F0D0008
			public static int MessageCenter_Item_Title_TextAppearance = 2131558408;
			
			// aapt resource value: 0x7F0D0009
			public static int MessageCenter_MessageNotSelected_TextAppearance = 2131558409;
			
			// aapt resource value: 0x7F0D000A
			public static int UrbanAirship = 2131558410;
			
			// aapt resource value: 0x7F0D000B
			public static int UrbanAirship_HelperActivity = 2131558411;
			
			// aapt resource value: 0x7F0D000C
			public static int UrbanAirship_InAppBanner = 2131558412;
			
			// aapt resource value: 0x7F0D000D
			public static int UrbanAirship_InAppBanner_Body = 2131558413;
			
			// aapt resource value: 0x7F0D000E
			public static int UrbanAirship_InAppBanner_Button = 2131558414;
			
			// aapt resource value: 0x7F0D000F
			public static int UrbanAirship_InAppBanner_ButtonLayout = 2131558415;
			
			// aapt resource value: 0x7F0D0010
			public static int UrbanAirship_InAppBanner_Heading = 2131558416;
			
			// aapt resource value: 0x7F0D0011
			public static int UrbanAirship_InAppBanner_Layout = 2131558417;
			
			// aapt resource value: 0x7F0D0012
			public static int UrbanAirship_InAppBanner_Layout_Bottom = 2131558418;
			
			// aapt resource value: 0x7F0D0013
			public static int UrbanAirship_InAppBanner_Layout_Top = 2131558419;
			
			// aapt resource value: 0x7F0D0014
			public static int UrbanAirship_InAppBanner_MediaView = 2131558420;
			
			// aapt resource value: 0x7F0D0015
			public static int UrbanAirship_InAppBanner_MediaView_Left = 2131558421;
			
			// aapt resource value: 0x7F0D0016
			public static int UrbanAirship_InAppBanner_MediaView_Right = 2131558422;
			
			// aapt resource value: 0x7F0D0017
			public static int UrbanAirship_InAppBanner_Pull = 2131558423;
			
			// aapt resource value: 0x7F0D0018
			public static int UrbanAirship_InAppBanner_Pull_Bottom = 2131558424;
			
			// aapt resource value: 0x7F0D0019
			public static int UrbanAirship_InAppBanner_Pull_Top = 2131558425;
			
			// aapt resource value: 0x7F0D001A
			public static int UrbanAirship_InAppFullscreen = 2131558426;
			
			// aapt resource value: 0x7F0D001B
			public static int UrbanAirship_InAppFullscreen_Activity = 2131558427;
			
			// aapt resource value: 0x7F0D001C
			public static int UrbanAirship_InAppFullscreen_Body = 2131558428;
			
			// aapt resource value: 0x7F0D001D
			public static int UrbanAirship_InAppFullscreen_Body_HeaderBodyMedia = 2131558429;
			
			// aapt resource value: 0x7F0D001E
			public static int UrbanAirship_InAppFullscreen_Body_HeaderMediaBody = 2131558430;
			
			// aapt resource value: 0x7F0D001F
			public static int UrbanAirship_InAppFullscreen_Body_MediaHeaderBody = 2131558431;
			
			// aapt resource value: 0x7F0D0020
			public static int UrbanAirship_InAppFullscreen_Button = 2131558432;
			
			// aapt resource value: 0x7F0D0021
			public static int UrbanAirship_InAppFullscreen_ButtonLayout = 2131558433;
			
			// aapt resource value: 0x7F0D0022
			public static int UrbanAirship_InAppFullscreen_DismissButton = 2131558434;
			
			// aapt resource value: 0x7F0D0023
			public static int UrbanAirship_InAppFullscreen_DismissButtonHolder = 2131558435;
			
			// aapt resource value: 0x7F0D0024
			public static int UrbanAirship_InAppFullscreen_Footer = 2131558436;
			
			// aapt resource value: 0x7F0D0025
			public static int UrbanAirship_InAppFullscreen_FooterHolder = 2131558437;
			
			// aapt resource value: 0x7F0D0026
			public static int UrbanAirship_InAppFullscreen_Heading = 2131558438;
			
			// aapt resource value: 0x7F0D0027
			public static int UrbanAirship_InAppFullscreen_Heading_HeaderBodyMedia = 2131558439;
			
			// aapt resource value: 0x7F0D0028
			public static int UrbanAirship_InAppFullscreen_Heading_HeaderMediaBody = 2131558440;
			
			// aapt resource value: 0x7F0D0029
			public static int UrbanAirship_InAppFullscreen_Heading_MediaHeaderBody = 2131558441;
			
			// aapt resource value: 0x7F0D002A
			public static int UrbanAirship_InAppFullscreen_Layout = 2131558442;
			
			// aapt resource value: 0x7F0D002B
			public static int UrbanAirship_InAppFullscreen_Layout_HeaderBodyMedia = 2131558443;
			
			// aapt resource value: 0x7F0D002C
			public static int UrbanAirship_InAppFullscreen_Layout_HeaderMediaBody = 2131558444;
			
			// aapt resource value: 0x7F0D002D
			public static int UrbanAirship_InAppFullscreen_Layout_MediaHeaderBody = 2131558445;
			
			// aapt resource value: 0x7F0D002E
			public static int UrbanAirship_InAppFullscreen_MediaView = 2131558446;
			
			// aapt resource value: 0x7F0D002F
			public static int UrbanAirship_InAppFullscreen_MediaView_HeaderBodyMedia = 2131558447;
			
			// aapt resource value: 0x7F0D0030
			public static int UrbanAirship_InAppFullscreen_MediaView_HeaderMediaBody = 2131558448;
			
			// aapt resource value: 0x7F0D0031
			public static int UrbanAirship_InAppFullscreen_MediaView_MediaHeaderBody = 2131558449;
			
			// aapt resource value: 0x7F0D0032
			public static int UrbanAirship_InAppFullscreen_ScrollView = 2131558450;
			
			// aapt resource value: 0x7F0D0033
			public static int UrbanAirship_InAppHtml = 2131558451;
			
			// aapt resource value: 0x7F0D0034
			public static int UrbanAirship_InAppHtml_Activity = 2131558452;
			
			// aapt resource value: 0x7F0D0035
			public static int UrbanAirship_InAppHtml_Activity_Fullscreen = 2131558453;
			
			// aapt resource value: 0x7F0D0036
			public static int UrbanAirship_InAppHtml_Content = 2131558454;
			
			// aapt resource value: 0x7F0D0037
			public static int UrbanAirship_InAppHtml_Content_Fullscreen = 2131558455;
			
			// aapt resource value: 0x7F0D0038
			public static int UrbanAirship_InAppHtml_DismissButton = 2131558456;
			
			// aapt resource value: 0x7F0D0039
			public static int UrbanAirship_InAppHtml_Layout = 2131558457;
			
			// aapt resource value: 0x7F0D003A
			public static int UrbanAirship_InAppHtml_Layout_Fullscreen = 2131558458;
			
			// aapt resource value: 0x7F0D003B
			public static int UrbanAirship_InAppHtml_Progress = 2131558459;
			
			// aapt resource value: 0x7F0D003C
			public static int UrbanAirship_InAppHtml_WebView = 2131558460;
			
			// aapt resource value: 0x7F0D003D
			public static int UrbanAirship_InAppModal = 2131558461;
			
			// aapt resource value: 0x7F0D003E
			public static int UrbanAirship_InAppModal_Activity = 2131558462;
			
			// aapt resource value: 0x7F0D003F
			public static int UrbanAirship_InAppModal_Activity_Fullscreen = 2131558463;
			
			// aapt resource value: 0x7F0D0040
			public static int UrbanAirship_InAppModal_Body = 2131558464;
			
			// aapt resource value: 0x7F0D0041
			public static int UrbanAirship_InAppModal_Body_HeaderBodyMedia = 2131558465;
			
			// aapt resource value: 0x7F0D0042
			public static int UrbanAirship_InAppModal_Body_HeaderMediaBody = 2131558466;
			
			// aapt resource value: 0x7F0D0043
			public static int UrbanAirship_InAppModal_Body_MediaHeaderBody = 2131558467;
			
			// aapt resource value: 0x7F0D0044
			public static int UrbanAirship_InAppModal_Button = 2131558468;
			
			// aapt resource value: 0x7F0D0045
			public static int UrbanAirship_InAppModal_ButtonLayout = 2131558469;
			
			// aapt resource value: 0x7F0D0046
			public static int UrbanAirship_InAppModal_Content = 2131558470;
			
			// aapt resource value: 0x7F0D0047
			public static int UrbanAirship_InAppModal_Content_HeaderBodyMedia = 2131558471;
			
			// aapt resource value: 0x7F0D0048
			public static int UrbanAirship_InAppModal_Content_HeaderMediaBody = 2131558472;
			
			// aapt resource value: 0x7F0D0049
			public static int UrbanAirship_InAppModal_Content_MediaHeaderBody = 2131558473;
			
			// aapt resource value: 0x7F0D004A
			public static int UrbanAirship_InAppModal_DismissButton = 2131558474;
			
			// aapt resource value: 0x7F0D004B
			public static int UrbanAirship_InAppModal_DismissButton_Fullscreen = 2131558475;
			
			// aapt resource value: 0x7F0D004C
			public static int UrbanAirship_InAppModal_Footer = 2131558476;
			
			// aapt resource value: 0x7F0D004D
			public static int UrbanAirship_InAppModal_FooterHolder = 2131558477;
			
			// aapt resource value: 0x7F0D004E
			public static int UrbanAirship_InAppModal_Heading = 2131558478;
			
			// aapt resource value: 0x7F0D004F
			public static int UrbanAirship_InAppModal_Heading_HeaderBodyMedia = 2131558479;
			
			// aapt resource value: 0x7F0D0050
			public static int UrbanAirship_InAppModal_Heading_HeaderMediaBody = 2131558480;
			
			// aapt resource value: 0x7F0D0051
			public static int UrbanAirship_InAppModal_Heading_MediaHeaderBody = 2131558481;
			
			// aapt resource value: 0x7F0D0052
			public static int UrbanAirship_InAppModal_Layout = 2131558482;
			
			// aapt resource value: 0x7F0D0053
			public static int UrbanAirship_InAppModal_Layout_Fullscreen = 2131558483;
			
			// aapt resource value: 0x7F0D0054
			public static int UrbanAirship_InAppModal_MediaView = 2131558484;
			
			// aapt resource value: 0x7F0D0055
			public static int UrbanAirship_InAppModal_MediaView_HeaderBodyMedia = 2131558485;
			
			// aapt resource value: 0x7F0D0056
			public static int UrbanAirship_InAppModal_MediaView_HeaderMediaBody = 2131558486;
			
			// aapt resource value: 0x7F0D0057
			public static int UrbanAirship_InAppModal_MediaView_MediaHeaderBody = 2131558487;
			
			// aapt resource value: 0x7F0D0058
			public static int UrbanAirship_InAppModal_ScrollView = 2131558488;
			
			// aapt resource value: 0x7F0D0059
			public static int UrbanAirship_RateAppActivity = 2131558489;
			
			// aapt resource value: 0x7F0D005A
			public static int Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131558490;
			
			// aapt resource value: 0x7F0D005B
			public static int Widget_UrbanAirship_MessageCenter_Item_Container = 2131558491;
			
			// aapt resource value: 0x7F0D005C
			public static int Widget_UrbanAirship_MessageCenter_Item_Date = 2131558492;
			
			// aapt resource value: 0x7F0D005D
			public static int Widget_UrbanAirship_MessageCenter_Item_Icon = 2131558493;
			
			// aapt resource value: 0x7F0D005E
			public static int Widget_UrbanAirship_MessageCenter_Item_Title = 2131558494;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F030000,0x7F030001,0x7F030002,0x7F030003,0x7F030004,0x7F030005,0x7F030006,0x7F030007,0x7F030009,0x7F03000A }
			public static int[] MessageCenter = new int[] {
					2130903040,
					2130903041,
					2130903042,
					2130903043,
					2130903044,
					2130903045,
					2130903046,
					2130903047,
					2130903049,
					2130903050};
			
			// aapt resource value: 0
			public static int MessageCenter_messageCenterDividerColor = 0;
			
			// aapt resource value: 1
			public static int MessageCenter_messageCenterEmptyMessageText = 1;
			
			// aapt resource value: 2
			public static int MessageCenter_messageCenterEmptyMessageTextAppearance = 2;
			
			// aapt resource value: 3
			public static int MessageCenter_messageCenterItemBackground = 3;
			
			// aapt resource value: 4
			public static int MessageCenter_messageCenterItemDateTextAppearance = 4;
			
			// aapt resource value: 5
			public static int MessageCenter_messageCenterItemIconEnabled = 5;
			
			// aapt resource value: 6
			public static int MessageCenter_messageCenterItemIconPlaceholder = 6;
			
			// aapt resource value: 7
			public static int MessageCenter_messageCenterItemTitleTextAppearance = 7;
			
			// aapt resource value: 8
			public static int MessageCenter_messageNotSelectedText = 8;
			
			// aapt resource value: 9
			public static int MessageCenter_messageNotSelectedTextAppearance = 9;
			
			// aapt resource value: { 0x7F03000C }
			public static int[] States = new int[] {
					2130903052};
			
			// aapt resource value: 0
			public static int States_ua_state_highlighted = 0;
			
			// aapt resource value: { 0x7F030008 }
			public static int[] Theme = new int[] {
					2130903048};
			
			// aapt resource value: 0
			public static int Theme_messageCenterStyle = 0;
			
			// aapt resource value: { 0x7F03000B }
			public static int[] UAWebView = new int[] {
					2130903051};
			
			// aapt resource value: 0
			public static int UAWebView_mixed_content_mode = 0;
			
			// aapt resource value: { 0x1010001,0x1010002 }
			public static int[] UrbanAirshipActionButton = new int[] {
					16842753,
					16842754};
			
			// aapt resource value: 1
			public static int UrbanAirshipActionButton_android_icon = 1;
			
			// aapt resource value: 0
			public static int UrbanAirshipActionButton_android_label = 0;
			
			// aapt resource value: { 0x7F03000D,0x7F030010,0x7F030011 }
			public static int[] UrbanAirshipInAppButtonLayout = new int[] {
					2130903053,
					2130903056,
					2130903057};
			
			// aapt resource value: 0
			public static int UrbanAirshipInAppButtonLayout_urbanAirshipButtonLayoutResourceId = 0;
			
			// aapt resource value: 1
			public static int UrbanAirshipInAppButtonLayout_urbanAirshipSeparatedSpaceWidth = 1;
			
			// aapt resource value: 2
			public static int UrbanAirshipInAppButtonLayout_urbanAirshipStackedSpaceHeight = 2;
			
			// aapt resource value: { 0x7F03000E,0x7F03000F }
			public static int[] UrbanAirshipLayout = new int[] {
					2130903054,
					2130903055};
			
			// aapt resource value: 0
			public static int UrbanAirshipLayout_urbanAirshipMaxHeight = 0;
			
			// aapt resource value: 1
			public static int UrbanAirshipLayout_urbanAirshipMaxWidth = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0F0000
			public static int ua_default_actions = 2131689472;
			
			// aapt resource value: 0x7F0F0001
			public static int ua_default_channels = 2131689473;
			
			// aapt resource value: 0x7F0F0003
			public static int ua_notification_buttons = 2131689475;
			
			// aapt resource value: 0x7F0F0002
			public static int ua_notification_button_overrides = 2131689474;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
