#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AirshipBindings.NETStandard.Resource", IsApplication=false)]

namespace AirshipBindings.NETStandard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int ua_iam_fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int ua_iam_fade_out = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public static int ua_iam_slide_in_bottom = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int ua_iam_slide_in_top = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int ua_iam_slide_out_bottom = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int ua_iam_slide_out_top = 2131034115;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public static int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public static int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public static int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public static int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int fontWeight = 2130771976;
			
			// aapt resource value: 0x7f010010
			public static int messageCenterDividerColor = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public static int messageCenterEmptyMessageText = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public static int messageCenterEmptyMessageTextAppearance = 2130771982;
			
			// aapt resource value: 0x7f010009
			public static int messageCenterItemBackground = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public static int messageCenterItemDateTextAppearance = 2130771979;
			
			// aapt resource value: 0x7f010011
			public static int messageCenterItemIconEnabled = 2130771985;
			
			// aapt resource value: 0x7f010012
			public static int messageCenterItemIconPlaceholder = 2130771986;
			
			// aapt resource value: 0x7f01000a
			public static int messageCenterItemTitleTextAppearance = 2130771978;
			
			// aapt resource value: 0x7f010014
			public static int messageCenterStyle = 2130771988;
			
			// aapt resource value: 0x7f01000d
			public static int messageNotSelectedText = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public static int messageNotSelectedTextAppearance = 2130771980;
			
			// aapt resource value: 0x7f010015
			public static int mixed_content_mode = 2130771989;
			
			// aapt resource value: 0x7f010013
			public static int ua_state_highlighted = 2130771987;
			
			// aapt resource value: 0x7f010016
			public static int urbanAirshipButtonLayoutResourceId = 2130771990;
			
			// aapt resource value: 0x7f01001a
			public static int urbanAirshipMaxHeight = 2130771994;
			
			// aapt resource value: 0x7f010019
			public static int urbanAirshipMaxWidth = 2130771993;
			
			// aapt resource value: 0x7f010018
			public static int urbanAirshipSeparatedSpaceWidth = 2130771992;
			
			// aapt resource value: 0x7f010017
			public static int urbanAirshipStackedSpaceHeight = 2130771991;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0c0000
			public static int abc_action_bar_embed_tabs = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public static int ua_iam_html_allow_fullscreen_display = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public static int ua_iam_modal_allow_fullscreen_display = 2131492866;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090003
			public static int notification_action_color_filter = 2131296259;
			
			// aapt resource value: 0x7f090004
			public static int notification_icon_bg_color = 2131296260;
			
			// aapt resource value: 0x7f090000
			public static int notification_material_background_media_default_color = 2131296256;
			
			// aapt resource value: 0x7f090001
			public static int primary_text_default_material_dark = 2131296257;
			
			// aapt resource value: 0x7f090005
			public static int ripple_material_light = 2131296261;
			
			// aapt resource value: 0x7f090002
			public static int secondary_text_default_material_dark = 2131296258;
			
			// aapt resource value: 0x7f090006
			public static int secondary_text_default_material_light = 2131296262;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0d0004
			public static int compat_button_inset_horizontal_material = 2131558404;
			
			// aapt resource value: 0x7f0d0005
			public static int compat_button_inset_vertical_material = 2131558405;
			
			// aapt resource value: 0x7f0d0006
			public static int compat_button_padding_horizontal_material = 2131558406;
			
			// aapt resource value: 0x7f0d0007
			public static int compat_button_padding_vertical_material = 2131558407;
			
			// aapt resource value: 0x7f0d0008
			public static int compat_control_corner_material = 2131558408;
			
			// aapt resource value: 0x7f0d0009
			public static int notification_action_icon_size = 2131558409;
			
			// aapt resource value: 0x7f0d000a
			public static int notification_action_text_size = 2131558410;
			
			// aapt resource value: 0x7f0d000b
			public static int notification_big_circle_margin = 2131558411;
			
			// aapt resource value: 0x7f0d0001
			public static int notification_content_margin_start = 2131558401;
			
			// aapt resource value: 0x7f0d000c
			public static int notification_large_icon_height = 2131558412;
			
			// aapt resource value: 0x7f0d000d
			public static int notification_large_icon_width = 2131558413;
			
			// aapt resource value: 0x7f0d0002
			public static int notification_main_column_padding_top = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public static int notification_media_narrow_margin = 2131558403;
			
			// aapt resource value: 0x7f0d000e
			public static int notification_right_icon_size = 2131558414;
			
			// aapt resource value: 0x7f0d0000
			public static int notification_right_side_padding_top = 2131558400;
			
			// aapt resource value: 0x7f0d000f
			public static int notification_small_icon_background_padding = 2131558415;
			
			// aapt resource value: 0x7f0d0010
			public static int notification_small_icon_size_as_large = 2131558416;
			
			// aapt resource value: 0x7f0d0011
			public static int notification_subtext_size = 2131558417;
			
			// aapt resource value: 0x7f0d0012
			public static int notification_top_pad = 2131558418;
			
			// aapt resource value: 0x7f0d0013
			public static int notification_top_pad_large_text = 2131558419;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f020026
			public static int notification_template_icon_bg = 2130837542;
			
			// aapt resource value: 0x7f020027
			public static int notification_template_icon_low_bg = 2130837543;
			
			// aapt resource value: 0x7f020008
			public static int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int notify_panel_notification_icon_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int ua_iam_banner_pull_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int ua_iam_dismiss_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int ua_ic_close = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int ua_ic_close_white = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int ua_ic_image_placeholder = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int ua_ic_notification_button_accept = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int ua_ic_notification_button_add = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int ua_ic_notification_button_book = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int ua_ic_notification_button_cart = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int ua_ic_notification_button_copy = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int ua_ic_notification_button_decline = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int ua_ic_notification_button_download = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int ua_ic_notification_button_event = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int ua_ic_notification_button_follow = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int ua_ic_notification_button_happy = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int ua_ic_notification_button_info = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int ua_ic_notification_button_open_browser = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int ua_ic_notification_button_remind = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int ua_ic_notification_button_sad = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int ua_ic_notification_button_save = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int ua_ic_notification_button_search = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int ua_ic_notification_button_send = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int ua_ic_notification_button_share = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int ua_ic_notification_button_thumbs_down = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int ua_ic_notification_button_thumbs_up = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int ua_ic_notification_button_unfollow = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int ua_ic_urbanairship_notification = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int ua_item_mc_background = 2130837541;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0e0011
			public static int action0 = 2131623953;
			
			// aapt resource value: 0x7f0e000e
			public static int action_container = 2131623950;
			
			// aapt resource value: 0x7f0e0015
			public static int action_divider = 2131623957;
			
			// aapt resource value: 0x7f0e000f
			public static int action_image = 2131623951;
			
			// aapt resource value: 0x7f0e0010
			public static int action_text = 2131623952;
			
			// aapt resource value: 0x7f0e001f
			public static int actions = 2131623967;
			
			// aapt resource value: 0x7f0e000b
			public static int always_allow = 2131623947;
			
			// aapt resource value: 0x7f0e0006
			public static int async = 2131623942;
			
			// aapt resource value: 0x7f0e0031
			public static int banner = 2131623985;
			
			// aapt resource value: 0x7f0e0033
			public static int banner_content = 2131623987;
			
			// aapt resource value: 0x7f0e0032
			public static int banner_pull = 2131623986;
			
			// aapt resource value: 0x7f0e0007
			public static int blocking = 2131623943;
			
			// aapt resource value: 0x7f0e0038
			public static int body = 2131623992;
			
			// aapt resource value: 0x7f0e0035
			public static int buttons = 2131623989;
			
			// aapt resource value: 0x7f0e0012
			public static int cancel_action = 2131623954;
			
			// aapt resource value: 0x7f0e0022
			public static int channel_capture_title = 2131623970;
			
			// aapt resource value: 0x7f0e0023
			public static int channel_id = 2131623971;
			
			// aapt resource value: 0x7f0e0027
			public static int channel_information = 2131623975;
			
			// aapt resource value: 0x7f0e0041
			public static int checkbox = 2131624001;
			
			// aapt resource value: 0x7f0e001a
			public static int chronometer = 2131623962;
			
			// aapt resource value: 0x7f0e0029
			public static int close_button = 2131623977;
			
			// aapt resource value: 0x7f0e000c
			public static int compatibility_mode = 2131623948;
			
			// aapt resource value: 0x7f0e002b
			public static int container = 2131623979;
			
			// aapt resource value: 0x7f0e0028
			public static int content_holder = 2131623976;
			
			// aapt resource value: 0x7f0e0025
			public static int copy_button = 2131623973;
			
			// aapt resource value: 0x7f0e0042
			public static int date = 2131624002;
			
			// aapt resource value: 0x7f0e0045
			public static int delete = 2131624005;
			
			// aapt resource value: 0x7f0e003b
			public static int dismiss = 2131623995;
			
			// aapt resource value: 0x7f0e0021
			public static int end_padder = 2131623969;
			
			// aapt resource value: 0x7f0e002d
			public static int error = 2131623981;
			
			// aapt resource value: 0x7f0e002e
			public static int error_message = 2131623982;
			
			// aapt resource value: 0x7f0e003a
			public static int footer = 2131623994;
			
			// aapt resource value: 0x7f0e0039
			public static int footer_holder = 2131623993;
			
			// aapt resource value: 0x7f0e0008
			public static int forever = 2131623944;
			
			// aapt resource value: 0x7f0e0037
			public static int heading = 2131623991;
			
			// aapt resource value: 0x7f0e001c
			public static int icon = 2131623964;
			
			// aapt resource value: 0x7f0e0020
			public static int icon_group = 2131623968;
			
			// aapt resource value: 0x7f0e0043
			public static int image = 2131624003;
			
			// aapt resource value: 0x7f0e001b
			public static int info = 2131623963;
			
			// aapt resource value: 0x7f0e0009
			public static int italic = 2131623945;
			
			// aapt resource value: 0x7f0e0000
			public static int line1 = 2131623936;
			
			// aapt resource value: 0x7f0e0001
			public static int line3 = 2131623937;
			
			// aapt resource value: 0x7f0e0044
			public static int mark_read = 2131624004;
			
			// aapt resource value: 0x7f0e0036
			public static int media = 2131623990;
			
			// aapt resource value: 0x7f0e0014
			public static int media_actions = 2131623956;
			
			// aapt resource value: 0x7f0e002c
			public static int message_container = 2131623980;
			
			// aapt resource value: 0x7f0e002a
			public static int message_list_container = 2131623978;
			
			// aapt resource value: 0x7f0e003e
			public static int modal = 2131623998;
			
			// aapt resource value: 0x7f0e003f
			public static int modal_content = 2131623999;
			
			// aapt resource value: 0x7f0e000d
			public static int never_allow = 2131623949;
			
			// aapt resource value: 0x7f0e000a
			public static int normal = 2131623946;
			
			// aapt resource value: 0x7f0e001e
			public static int notification_background = 2131623966;
			
			// aapt resource value: 0x7f0e0017
			public static int notification_main_column = 2131623959;
			
			// aapt resource value: 0x7f0e0016
			public static int notification_main_column_container = 2131623958;
			
			// aapt resource value: 0x7f0e0026
			public static int open_button = 2131623974;
			
			// aapt resource value: 0x7f0e003d
			public static int progress = 2131623997;
			
			// aapt resource value: 0x7f0e002f
			public static int retry_button = 2131623983;
			
			// aapt resource value: 0x7f0e001d
			public static int right_icon = 2131623965;
			
			// aapt resource value: 0x7f0e0018
			public static int right_side = 2131623960;
			
			// aapt resource value: 0x7f0e0046
			public static int select_all = 2131624006;
			
			// aapt resource value: 0x7f0e0024
			public static int share_button = 2131623972;
			
			// aapt resource value: 0x7f0e0013
			public static int status_bar_latest_event_content = 2131623955;
			
			// aapt resource value: 0x7f0e0030
			public static int swipe_container = 2131623984;
			
			// aapt resource value: 0x7f0e0002
			public static int tag_transition_group = 2131623938;
			
			// aapt resource value: 0x7f0e0003
			public static int text = 2131623939;
			
			// aapt resource value: 0x7f0e0004
			public static int text2 = 2131623940;
			
			// aapt resource value: 0x7f0e0019
			public static int time = 2131623961;
			
			// aapt resource value: 0x7f0e0005
			public static int title = 2131623941;
			
			// aapt resource value: 0x7f0e0034
			public static int ua_iam_banner_content_left_image = 2131623988;
			
			// aapt resource value: 0x7f0e0040
			public static int ua_iam_modal_header_body_media = 2131624000;
			
			// aapt resource value: 0x7f0e003c
			public static int web_view = 2131623996;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public static int cancel_button_image_alpha = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public static int status_bar_notification_info_maxnum = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public static int ua_iam_banner_animation_duration = 2131361794;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int notification_action = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int notification_action_tombstone = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int notification_media_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int notification_media_cancel_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int notification_template_big_media = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int notification_template_big_media_custom = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int notification_template_big_media_narrow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int notification_template_big_media_narrow_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int notification_template_custom_big = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int notification_template_icon_group = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int notification_template_lines_media = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int notification_template_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int notification_template_media_custom = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int notification_template_part_chronometer = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int notification_template_part_time = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int ua_activity_channel_capture = 2130903055;
			
			// aapt resource value: 0x7f030010
			public static int ua_activity_landing_page = 2130903056;
			
			// aapt resource value: 0x7f030011
			public static int ua_fragment_mc = 2130903057;
			
			// aapt resource value: 0x7f030012
			public static int ua_fragment_message = 2130903058;
			
			// aapt resource value: 0x7f030013
			public static int ua_fragment_message_list = 2130903059;
			
			// aapt resource value: 0x7f030014
			public static int ua_fragment_no_message_selected = 2130903060;
			
			// aapt resource value: 0x7f030015
			public static int ua_iam_banner_bottom = 2130903061;
			
			// aapt resource value: 0x7f030016
			public static int ua_iam_banner_button = 2130903062;
			
			// aapt resource value: 0x7f030017
			public static int ua_iam_banner_content_left_media = 2130903063;
			
			// aapt resource value: 0x7f030018
			public static int ua_iam_banner_content_right_media = 2130903064;
			
			// aapt resource value: 0x7f030019
			public static int ua_iam_banner_top = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public static int ua_iam_fullscreen_button = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public static int ua_iam_fullscreen_header_body_media = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public static int ua_iam_fullscreen_header_media_body = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public static int ua_iam_fullscreen_media_header_body = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public static int ua_iam_html = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public static int ua_iam_html_fullscreen = 2130903071;
			
			// aapt resource value: 0x7f030020
			public static int ua_iam_modal = 2130903072;
			
			// aapt resource value: 0x7f030021
			public static int ua_iam_modal_button = 2130903073;
			
			// aapt resource value: 0x7f030022
			public static int ua_iam_modal_fullscreen = 2130903074;
			
			// aapt resource value: 0x7f030023
			public static int ua_iam_modal_header_body_media = 2130903075;
			
			// aapt resource value: 0x7f030024
			public static int ua_iam_modal_header_media_body = 2130903076;
			
			// aapt resource value: 0x7f030025
			public static int ua_iam_modal_media_header_body = 2130903077;
			
			// aapt resource value: 0x7f030026
			public static int ua_item_mc = 2130903078;
			
			// aapt resource value: 0x7f030027
			public static int ua_item_mc_content = 2130903079;
			
			// aapt resource value: 0x7f030028
			public static int ua_item_mc_icon_content = 2130903080;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f100000
			public static int ua_mc_action_mode = 2131755008;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f0f0000
			public static int ua_selected_count = 2131689472;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f070000
			public static int ua_blank_favicon = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int ua_native_bridge = 2131165185;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b003a
			public static int library_name = 2131427386;
			
			// aapt resource value: 0x7f0b0000
			public static int status_bar_notification_info_overflow = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public static int ua_cancel = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public static int ua_channel_copy_toast = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public static int ua_channel_id = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public static int ua_channel_notification_ticker = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public static int ua_connection_error = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public static int ua_content_error = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public static int ua_default_channel_description = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public static int ua_default_channel_name = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public static int ua_delete = 2131427337;
			
			// aapt resource value: 0x7f0b0036
			public static int ua_emoji_happy = 2131427382;
			
			// aapt resource value: 0x7f0b0037
			public static int ua_emoji_sad = 2131427383;
			
			// aapt resource value: 0x7f0b0038
			public static int ua_emoji_thumbs_down = 2131427384;
			
			// aapt resource value: 0x7f0b0039
			public static int ua_emoji_thumbs_up = 2131427385;
			
			// aapt resource value: 0x7f0b000a
			public static int ua_empty_message_list = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public static int ua_mark_read = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public static int ua_mc_failed_to_load = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public static int ua_mc_no_longer_available = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public static int ua_message_center_title = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public static int ua_message_not_selected = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public static int ua_notification_button_accept = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public static int ua_notification_button_add = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public static int ua_notification_button_add_to_calendar = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public static int ua_notification_button_book_now = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public static int ua_notification_button_buy_now = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public static int ua_notification_button_copy = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public static int ua_notification_button_decline = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public static int ua_notification_button_dislike = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public static int ua_notification_button_download = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public static int ua_notification_button_follow = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public static int ua_notification_button_less_like = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public static int ua_notification_button_like = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public static int ua_notification_button_more_like = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public static int ua_notification_button_no = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public static int ua_notification_button_opt_in = 2131427358;
			
			// aapt resource value: 0x7f0b001f
			public static int ua_notification_button_opt_out = 2131427359;
			
			// aapt resource value: 0x7f0b0020
			public static int ua_notification_button_rate_now = 2131427360;
			
			// aapt resource value: 0x7f0b0021
			public static int ua_notification_button_remind = 2131427361;
			
			// aapt resource value: 0x7f0b0022
			public static int ua_notification_button_save = 2131427362;
			
			// aapt resource value: 0x7f0b0023
			public static int ua_notification_button_search = 2131427363;
			
			// aapt resource value: 0x7f0b0024
			public static int ua_notification_button_send_info = 2131427364;
			
			// aapt resource value: 0x7f0b0025
			public static int ua_notification_button_share = 2131427365;
			
			// aapt resource value: 0x7f0b0026
			public static int ua_notification_button_shop_now = 2131427366;
			
			// aapt resource value: 0x7f0b0027
			public static int ua_notification_button_tell_me_more = 2131427367;
			
			// aapt resource value: 0x7f0b0028
			public static int ua_notification_button_unfollow = 2131427368;
			
			// aapt resource value: 0x7f0b0029
			public static int ua_notification_button_yes = 2131427369;
			
			// aapt resource value: 0x7f0b002a
			public static int ua_ok = 2131427370;
			
			// aapt resource value: 0x7f0b002b
			public static int ua_open = 2131427371;
			
			// aapt resource value: 0x7f0b002c
			public static int ua_rate_app_action_default_body = 2131427372;
			
			// aapt resource value: 0x7f0b002d
			public static int ua_rate_app_action_default_rate_negative_button = 2131427373;
			
			// aapt resource value: 0x7f0b002e
			public static int ua_rate_app_action_default_rate_positive_button = 2131427374;
			
			// aapt resource value: 0x7f0b002f
			public static int ua_rate_app_action_default_title = 2131427375;
			
			// aapt resource value: 0x7f0b0030
			public static int ua_rate_app_action_generic_display_name = 2131427376;
			
			// aapt resource value: 0x7f0b0031
			public static int ua_refresh = 2131427377;
			
			// aapt resource value: 0x7f0b0032
			public static int ua_retry_button = 2131427378;
			
			// aapt resource value: 0x7f0b0033
			public static int ua_select_all = 2131427379;
			
			// aapt resource value: 0x7f0b0034
			public static int ua_select_none = 2131427380;
			
			// aapt resource value: 0x7f0b0035
			public static int ua_share_dialog_title = 2131427381;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f08000c
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Container = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Date = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Icon = 2131230735;
			
			// aapt resource value: 0x7f080010
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Title = 2131230736;
			
			// aapt resource value: 0x7f080011
			public static int MessageCenter = 2131230737;
			
			// aapt resource value: 0x7f080012
			public static int MessageCenter_EmptyMessage_TextAppearance = 2131230738;
			
			// aapt resource value: 0x7f080013
			public static int MessageCenter_Item_Date_TextAppearance = 2131230739;
			
			// aapt resource value: 0x7f080014
			public static int MessageCenter_Item_Title_TextAppearance = 2131230740;
			
			// aapt resource value: 0x7f080015
			public static int MessageCenter_MessageNotSelected_TextAppearance = 2131230741;
			
			// aapt resource value: 0x7f080005
			public static int TextAppearance_Compat_Notification = 2131230725;
			
			// aapt resource value: 0x7f080006
			public static int TextAppearance_Compat_Notification_Info = 2131230726;
			
			// aapt resource value: 0x7f080000
			public static int TextAppearance_Compat_Notification_Info_Media = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public static int TextAppearance_Compat_Notification_Line2 = 2131230731;
			
			// aapt resource value: 0x7f080004
			public static int TextAppearance_Compat_Notification_Line2_Media = 2131230724;
			
			// aapt resource value: 0x7f080001
			public static int TextAppearance_Compat_Notification_Media = 2131230721;
			
			// aapt resource value: 0x7f080007
			public static int TextAppearance_Compat_Notification_Time = 2131230727;
			
			// aapt resource value: 0x7f080002
			public static int TextAppearance_Compat_Notification_Time_Media = 2131230722;
			
			// aapt resource value: 0x7f080008
			public static int TextAppearance_Compat_Notification_Title = 2131230728;
			
			// aapt resource value: 0x7f080003
			public static int TextAppearance_Compat_Notification_Title_Media = 2131230723;
			
			// aapt resource value: 0x7f080016
			public static int UrbanAirship = 2131230742;
			
			// aapt resource value: 0x7f080017
			public static int UrbanAirship_HelperActivity = 2131230743;
			
			// aapt resource value: 0x7f080018
			public static int UrbanAirship_InAppBanner = 2131230744;
			
			// aapt resource value: 0x7f080019
			public static int UrbanAirship_InAppBanner_Body = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public static int UrbanAirship_InAppBanner_Button = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public static int UrbanAirship_InAppBanner_ButtonLayout = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public static int UrbanAirship_InAppBanner_Heading = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public static int UrbanAirship_InAppBanner_Layout = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public static int UrbanAirship_InAppBanner_Layout_Bottom = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public static int UrbanAirship_InAppBanner_Layout_Top = 2131230751;
			
			// aapt resource value: 0x7f080020
			public static int UrbanAirship_InAppBanner_MediaView = 2131230752;
			
			// aapt resource value: 0x7f080021
			public static int UrbanAirship_InAppBanner_MediaView_Left = 2131230753;
			
			// aapt resource value: 0x7f080022
			public static int UrbanAirship_InAppBanner_MediaView_Right = 2131230754;
			
			// aapt resource value: 0x7f080023
			public static int UrbanAirship_InAppBanner_Pull = 2131230755;
			
			// aapt resource value: 0x7f080024
			public static int UrbanAirship_InAppBanner_Pull_Bottom = 2131230756;
			
			// aapt resource value: 0x7f080025
			public static int UrbanAirship_InAppBanner_Pull_Top = 2131230757;
			
			// aapt resource value: 0x7f080026
			public static int UrbanAirship_InAppFullscreen = 2131230758;
			
			// aapt resource value: 0x7f080027
			public static int UrbanAirship_InAppFullscreen_Activity = 2131230759;
			
			// aapt resource value: 0x7f080028
			public static int UrbanAirship_InAppFullscreen_Body = 2131230760;
			
			// aapt resource value: 0x7f080029
			public static int UrbanAirship_InAppFullscreen_Body_HeaderBodyMedia = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public static int UrbanAirship_InAppFullscreen_Body_HeaderMediaBody = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public static int UrbanAirship_InAppFullscreen_Body_MediaHeaderBody = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public static int UrbanAirship_InAppFullscreen_Button = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public static int UrbanAirship_InAppFullscreen_ButtonLayout = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public static int UrbanAirship_InAppFullscreen_DismissButton = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public static int UrbanAirship_InAppFullscreen_DismissButtonHolder = 2131230767;
			
			// aapt resource value: 0x7f080030
			public static int UrbanAirship_InAppFullscreen_Footer = 2131230768;
			
			// aapt resource value: 0x7f080031
			public static int UrbanAirship_InAppFullscreen_FooterHolder = 2131230769;
			
			// aapt resource value: 0x7f080032
			public static int UrbanAirship_InAppFullscreen_Heading = 2131230770;
			
			// aapt resource value: 0x7f080033
			public static int UrbanAirship_InAppFullscreen_Heading_HeaderBodyMedia = 2131230771;
			
			// aapt resource value: 0x7f080034
			public static int UrbanAirship_InAppFullscreen_Heading_HeaderMediaBody = 2131230772;
			
			// aapt resource value: 0x7f080035
			public static int UrbanAirship_InAppFullscreen_Heading_MediaHeaderBody = 2131230773;
			
			// aapt resource value: 0x7f080036
			public static int UrbanAirship_InAppFullscreen_Layout = 2131230774;
			
			// aapt resource value: 0x7f080037
			public static int UrbanAirship_InAppFullscreen_Layout_HeaderBodyMedia = 2131230775;
			
			// aapt resource value: 0x7f080038
			public static int UrbanAirship_InAppFullscreen_Layout_HeaderMediaBody = 2131230776;
			
			// aapt resource value: 0x7f080039
			public static int UrbanAirship_InAppFullscreen_Layout_MediaHeaderBody = 2131230777;
			
			// aapt resource value: 0x7f08003a
			public static int UrbanAirship_InAppFullscreen_MediaView = 2131230778;
			
			// aapt resource value: 0x7f08003b
			public static int UrbanAirship_InAppFullscreen_MediaView_HeaderBodyMedia = 2131230779;
			
			// aapt resource value: 0x7f08003c
			public static int UrbanAirship_InAppFullscreen_MediaView_HeaderMediaBody = 2131230780;
			
			// aapt resource value: 0x7f08003d
			public static int UrbanAirship_InAppFullscreen_MediaView_MediaHeaderBody = 2131230781;
			
			// aapt resource value: 0x7f08003e
			public static int UrbanAirship_InAppFullscreen_ScrollView = 2131230782;
			
			// aapt resource value: 0x7f08003f
			public static int UrbanAirship_InAppHtml = 2131230783;
			
			// aapt resource value: 0x7f080040
			public static int UrbanAirship_InAppHtml_Activity = 2131230784;
			
			// aapt resource value: 0x7f080041
			public static int UrbanAirship_InAppHtml_Activity_Fullscreen = 2131230785;
			
			// aapt resource value: 0x7f080042
			public static int UrbanAirship_InAppHtml_Content = 2131230786;
			
			// aapt resource value: 0x7f080043
			public static int UrbanAirship_InAppHtml_Content_Fullscreen = 2131230787;
			
			// aapt resource value: 0x7f080044
			public static int UrbanAirship_InAppHtml_DismissButton = 2131230788;
			
			// aapt resource value: 0x7f080045
			public static int UrbanAirship_InAppHtml_Layout = 2131230789;
			
			// aapt resource value: 0x7f080046
			public static int UrbanAirship_InAppHtml_Layout_Fullscreen = 2131230790;
			
			// aapt resource value: 0x7f080047
			public static int UrbanAirship_InAppHtml_Progress = 2131230791;
			
			// aapt resource value: 0x7f080048
			public static int UrbanAirship_InAppHtml_WebView = 2131230792;
			
			// aapt resource value: 0x7f080049
			public static int UrbanAirship_InAppModal = 2131230793;
			
			// aapt resource value: 0x7f08004a
			public static int UrbanAirship_InAppModal_Activity = 2131230794;
			
			// aapt resource value: 0x7f08004b
			public static int UrbanAirship_InAppModal_Activity_Fullscreen = 2131230795;
			
			// aapt resource value: 0x7f08004c
			public static int UrbanAirship_InAppModal_Body = 2131230796;
			
			// aapt resource value: 0x7f08004d
			public static int UrbanAirship_InAppModal_Body_HeaderBodyMedia = 2131230797;
			
			// aapt resource value: 0x7f08004e
			public static int UrbanAirship_InAppModal_Body_HeaderMediaBody = 2131230798;
			
			// aapt resource value: 0x7f08004f
			public static int UrbanAirship_InAppModal_Body_MediaHeaderBody = 2131230799;
			
			// aapt resource value: 0x7f080050
			public static int UrbanAirship_InAppModal_Button = 2131230800;
			
			// aapt resource value: 0x7f080051
			public static int UrbanAirship_InAppModal_ButtonLayout = 2131230801;
			
			// aapt resource value: 0x7f080052
			public static int UrbanAirship_InAppModal_Content = 2131230802;
			
			// aapt resource value: 0x7f080053
			public static int UrbanAirship_InAppModal_Content_HeaderBodyMedia = 2131230803;
			
			// aapt resource value: 0x7f080054
			public static int UrbanAirship_InAppModal_Content_HeaderMediaBody = 2131230804;
			
			// aapt resource value: 0x7f080055
			public static int UrbanAirship_InAppModal_Content_MediaHeaderBody = 2131230805;
			
			// aapt resource value: 0x7f080056
			public static int UrbanAirship_InAppModal_DismissButton = 2131230806;
			
			// aapt resource value: 0x7f080057
			public static int UrbanAirship_InAppModal_DismissButton_Fullscreen = 2131230807;
			
			// aapt resource value: 0x7f080058
			public static int UrbanAirship_InAppModal_Footer = 2131230808;
			
			// aapt resource value: 0x7f080059
			public static int UrbanAirship_InAppModal_FooterHolder = 2131230809;
			
			// aapt resource value: 0x7f08005a
			public static int UrbanAirship_InAppModal_Heading = 2131230810;
			
			// aapt resource value: 0x7f08005b
			public static int UrbanAirship_InAppModal_Heading_HeaderBodyMedia = 2131230811;
			
			// aapt resource value: 0x7f08005c
			public static int UrbanAirship_InAppModal_Heading_HeaderMediaBody = 2131230812;
			
			// aapt resource value: 0x7f08005d
			public static int UrbanAirship_InAppModal_Heading_MediaHeaderBody = 2131230813;
			
			// aapt resource value: 0x7f08005e
			public static int UrbanAirship_InAppModal_Layout = 2131230814;
			
			// aapt resource value: 0x7f08005f
			public static int UrbanAirship_InAppModal_Layout_Fullscreen = 2131230815;
			
			// aapt resource value: 0x7f080060
			public static int UrbanAirship_InAppModal_MediaView = 2131230816;
			
			// aapt resource value: 0x7f080061
			public static int UrbanAirship_InAppModal_MediaView_HeaderBodyMedia = 2131230817;
			
			// aapt resource value: 0x7f080062
			public static int UrbanAirship_InAppModal_MediaView_HeaderMediaBody = 2131230818;
			
			// aapt resource value: 0x7f080063
			public static int UrbanAirship_InAppModal_MediaView_MediaHeaderBody = 2131230819;
			
			// aapt resource value: 0x7f080064
			public static int UrbanAirship_InAppModal_ScrollView = 2131230820;
			
			// aapt resource value: 0x7f080065
			public static int UrbanAirship_LandingPageActivity = 2131230821;
			
			// aapt resource value: 0x7f080066
			public static int UrbanAirship_RateAppActivity = 2131230822;
			
			// aapt resource value: 0x7f080009
			public static int Widget_Compat_NotificationActionContainer = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public static int Widget_Compat_NotificationActionText = 2131230730;
			
			// aapt resource value: 0x7f080067
			public static int Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131230823;
			
			// aapt resource value: 0x7f080068
			public static int Widget_UrbanAirship_MessageCenter_Item_Container = 2131230824;
			
			// aapt resource value: 0x7f080069
			public static int Widget_UrbanAirship_MessageCenter_Item_Date = 2131230825;
			
			// aapt resource value: 0x7f08006a
			public static int Widget_UrbanAirship_MessageCenter_Item_Icon = 2131230826;
			
			// aapt resource value: 0x7f08006b
			public static int Widget_UrbanAirship_MessageCenter_Item_Title = 2131230827;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f060000
			public static int ua_default_actions = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int ua_default_channels = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int ua_notification_button_overrides = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int ua_notification_buttons = 2131099651;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public static int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public static int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public static int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public static int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public static int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public static int FontFamilyFont_fontWeight = 5;
			
			public static int[] MessageCenter = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 7
			public static int MessageCenter_messageCenterDividerColor = 7;
			
			// aapt resource value: 6
			public static int MessageCenter_messageCenterEmptyMessageText = 6;
			
			// aapt resource value: 5
			public static int MessageCenter_messageCenterEmptyMessageTextAppearance = 5;
			
			// aapt resource value: 0
			public static int MessageCenter_messageCenterItemBackground = 0;
			
			// aapt resource value: 2
			public static int MessageCenter_messageCenterItemDateTextAppearance = 2;
			
			// aapt resource value: 8
			public static int MessageCenter_messageCenterItemIconEnabled = 8;
			
			// aapt resource value: 9
			public static int MessageCenter_messageCenterItemIconPlaceholder = 9;
			
			// aapt resource value: 1
			public static int MessageCenter_messageCenterItemTitleTextAppearance = 1;
			
			// aapt resource value: 4
			public static int MessageCenter_messageNotSelectedText = 4;
			
			// aapt resource value: 3
			public static int MessageCenter_messageNotSelectedTextAppearance = 3;
			
			public static int[] States = new int[] {
					2130771987};
			
			// aapt resource value: 0
			public static int States_ua_state_highlighted = 0;
			
			public static int[] Theme = new int[] {
					2130771988};
			
			// aapt resource value: 0
			public static int Theme_messageCenterStyle = 0;
			
			public static int[] UAWebView = new int[] {
					2130771989};
			
			// aapt resource value: 0
			public static int UAWebView_mixed_content_mode = 0;
			
			public static int[] UrbanAirshipActionButton = new int[] {
					16842753,
					16842754};
			
			// aapt resource value: 1
			public static int UrbanAirshipActionButton_android_icon = 1;
			
			// aapt resource value: 0
			public static int UrbanAirshipActionButton_android_label = 0;
			
			public static int[] UrbanAirshipInAppButtonLayout = new int[] {
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 0
			public static int UrbanAirshipInAppButtonLayout_urbanAirshipButtonLayoutResourceId = 0;
			
			// aapt resource value: 2
			public static int UrbanAirshipInAppButtonLayout_urbanAirshipSeparatedSpaceWidth = 2;
			
			// aapt resource value: 1
			public static int UrbanAirshipInAppButtonLayout_urbanAirshipStackedSpaceHeight = 1;
			
			public static int[] UrbanAirshipLayout = new int[] {
					2130771993,
					2130771994};
			
			// aapt resource value: 1
			public static int UrbanAirshipLayout_urbanAirshipMaxHeight = 1;
			
			// aapt resource value: 0
			public static int UrbanAirshipLayout_urbanAirshipMaxWidth = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
