#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AirshipBindings.Portable.Resource", IsApplication=false)]

namespace AirshipBindings.Portable
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public static int ua_iam_slide_in_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int ua_iam_slide_in_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int ua_iam_slide_out_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int ua_iam_slide_out_top = 2130968579;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int bannerActionButtonTextAppearance = 2130771974;
			
			// aapt resource value: 0x7f010004
			public static int bannerDismissButtonDrawable = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int bannerFontPath = 2130771968;
			
			// aapt resource value: 0x7f010005
			public static int bannerNoDismissButton = 2130771973;
			
			// aapt resource value: 0x7f010002
			public static int bannerPrimaryColor = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int bannerSecondaryColor = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int bannerTextAppearance = 2130771969;
			
			// aapt resource value: 0x7f010016
			public static int inAppMessageBannerStyle = 2130771990;
			
			// aapt resource value: 0x7f010011
			public static int messageCenterDividerColor = 2130771985;
			
			// aapt resource value: 0x7f010010
			public static int messageCenterEmptyMessageText = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public static int messageCenterEmptyMessageTextAppearance = 2130771983;
			
			// aapt resource value: 0x7f01000a
			public static int messageCenterItemBackground = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public static int messageCenterItemDateTextAppearance = 2130771980;
			
			// aapt resource value: 0x7f010012
			public static int messageCenterItemIconEnabled = 2130771986;
			
			// aapt resource value: 0x7f010013
			public static int messageCenterItemIconPlaceholder = 2130771987;
			
			// aapt resource value: 0x7f01000b
			public static int messageCenterItemTitleTextAppearance = 2130771979;
			
			// aapt resource value: 0x7f010017
			public static int messageCenterStyle = 2130771991;
			
			// aapt resource value: 0x7f01000e
			public static int messageNotSelectedText = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public static int messageNotSelectedTextAppearance = 2130771981;
			
			// aapt resource value: 0x7f010018
			public static int mixed_content_mode = 2130771992;
			
			// aapt resource value: 0x7f010007
			public static int optCardBackgroundColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public static int optCardCornerRadius = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int optCardElevation = 2130771977;
			
			// aapt resource value: 0x7f010014
			public static int ua_state_highlighted = 2130771988;
			
			// aapt resource value: 0x7f010015
			public static int urbanAirshipFontPath = 2130771989;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090000
			public static int ua_iam_primary = 2131296256;
			
			// aapt resource value: 0x7f090001
			public static int ua_iam_secondary = 2131296257;
			
			// aapt resource value: 0x7f090002
			public static int urban_airship_blue = 2131296258;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0000
			public static int ua_iam_banner_corner_radius = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public static int ua_iam_banner_elevation = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public static int ua_iam_banner_width = 2131361794;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ua_iam_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ua_ic_close = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ua_ic_close_white_18dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ua_ic_image_placeholder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int ua_ic_notification_button_accept = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int ua_ic_notification_button_add = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int ua_ic_notification_button_book = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int ua_ic_notification_button_cart = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int ua_ic_notification_button_copy = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int ua_ic_notification_button_decline = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int ua_ic_notification_button_download = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int ua_ic_notification_button_event = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int ua_ic_notification_button_follow = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int ua_ic_notification_button_happy = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int ua_ic_notification_button_info = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int ua_ic_notification_button_open_browser = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int ua_ic_notification_button_remind = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int ua_ic_notification_button_sad = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int ua_ic_notification_button_save = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int ua_ic_notification_button_search = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int ua_ic_notification_button_send = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int ua_ic_notification_button_share = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int ua_ic_notification_button_thumbs_down = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int ua_ic_notification_button_thumbs_up = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int ua_ic_notification_button_unfollow = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int ua_ic_urbanairship_notification = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int ua_item_mc_background = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0e000c
			public static int action_button = 2131623948;
			
			// aapt resource value: 0x7f0e0010
			public static int action_buttons = 2131623952;
			
			// aapt resource value: 0x7f0e000f
			public static int action_divider = 2131623951;
			
			// aapt resource value: 0x7f0e000e
			public static int alert = 2131623950;
			
			// aapt resource value: 0x7f0e0000
			public static int always_allow = 2131623936;
			
			// aapt resource value: 0x7f0e0011
			public static int checkbox = 2131623953;
			
			// aapt resource value: 0x7f0e000d
			public static int close = 2131623949;
			
			// aapt resource value: 0x7f0e0004
			public static int close_button = 2131623940;
			
			// aapt resource value: 0x7f0e0001
			public static int compatibility_mode = 2131623937;
			
			// aapt resource value: 0x7f0e0007
			public static int container = 2131623943;
			
			// aapt resource value: 0x7f0e0003
			public static int content_holder = 2131623939;
			
			// aapt resource value: 0x7f0e0013
			public static int date = 2131623955;
			
			// aapt resource value: 0x7f0e0016
			public static int delete = 2131623958;
			
			// aapt resource value: 0x7f0e0009
			public static int error = 2131623945;
			
			// aapt resource value: 0x7f0e0014
			public static int image = 2131623956;
			
			// aapt resource value: 0x7f0e0005
			public static int in_app_message = 2131623941;
			
			// aapt resource value: 0x7f0e0015
			public static int mark_read = 2131623957;
			
			// aapt resource value: 0x7f0e0008
			public static int message_container = 2131623944;
			
			// aapt resource value: 0x7f0e0006
			public static int message_list_container = 2131623942;
			
			// aapt resource value: 0x7f0e0002
			public static int never_allow = 2131623938;
			
			// aapt resource value: 0x7f0e000a
			public static int retry_button = 2131623946;
			
			// aapt resource value: 0x7f0e0017
			public static int select_all = 2131623959;
			
			// aapt resource value: 0x7f0e000b
			public static int swipe_container = 2131623947;
			
			// aapt resource value: 0x7f0e0012
			public static int title = 2131623954;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public static int ua_iam_animation_duration = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int ua_activity_landing_page = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int ua_fragment_iam = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int ua_fragment_iam_card = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int ua_fragment_mc = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int ua_fragment_message = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int ua_fragment_message_list = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int ua_fragment_no_message_selected = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int ua_iam_button = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int ua_iam_content = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int ua_item_mc = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int ua_item_mc_content = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int ua_item_mc_icon_content = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0d0000
			public static int ua_mc_action_mode = 2131558400;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f070000
			public static int ua_selected_count = 2131165184;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public static int ua_native_bridge = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f08002d
			public static int library_name = 2131230765;
			
			// aapt resource value: 0x7f080000
			public static int ua_cancel = 2131230720;
			
			// aapt resource value: 0x7f080001
			public static int ua_channel_copy_toast = 2131230721;
			
			// aapt resource value: 0x7f080002
			public static int ua_channel_notification_ticker = 2131230722;
			
			// aapt resource value: 0x7f080003
			public static int ua_connection_error = 2131230723;
			
			// aapt resource value: 0x7f080004
			public static int ua_delete = 2131230724;
			
			// aapt resource value: 0x7f080029
			public static int ua_emoji_happy = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public static int ua_emoji_sad = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public static int ua_emoji_thumbs_down = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public static int ua_emoji_thumbs_up = 2131230764;
			
			// aapt resource value: 0x7f080005
			public static int ua_empty_message_list = 2131230725;
			
			// aapt resource value: 0x7f080006
			public static int ua_mark_read = 2131230726;
			
			// aapt resource value: 0x7f080007
			public static int ua_mc_failed_to_load = 2131230727;
			
			// aapt resource value: 0x7f080008
			public static int ua_message_center_title = 2131230728;
			
			// aapt resource value: 0x7f080009
			public static int ua_message_not_selected = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public static int ua_notification_button_accept = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public static int ua_notification_button_add = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public static int ua_notification_button_add_to_calendar = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public static int ua_notification_button_book_now = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public static int ua_notification_button_buy_now = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public static int ua_notification_button_copy = 2131230735;
			
			// aapt resource value: 0x7f080010
			public static int ua_notification_button_decline = 2131230736;
			
			// aapt resource value: 0x7f080011
			public static int ua_notification_button_dislike = 2131230737;
			
			// aapt resource value: 0x7f080012
			public static int ua_notification_button_download = 2131230738;
			
			// aapt resource value: 0x7f080013
			public static int ua_notification_button_follow = 2131230739;
			
			// aapt resource value: 0x7f080014
			public static int ua_notification_button_less_like = 2131230740;
			
			// aapt resource value: 0x7f080015
			public static int ua_notification_button_like = 2131230741;
			
			// aapt resource value: 0x7f080016
			public static int ua_notification_button_more_like = 2131230742;
			
			// aapt resource value: 0x7f080017
			public static int ua_notification_button_no = 2131230743;
			
			// aapt resource value: 0x7f080018
			public static int ua_notification_button_opt_in = 2131230744;
			
			// aapt resource value: 0x7f080019
			public static int ua_notification_button_opt_out = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public static int ua_notification_button_rate_now = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public static int ua_notification_button_remind = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public static int ua_notification_button_save = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public static int ua_notification_button_search = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public static int ua_notification_button_send_info = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public static int ua_notification_button_share = 2131230751;
			
			// aapt resource value: 0x7f080020
			public static int ua_notification_button_shop_now = 2131230752;
			
			// aapt resource value: 0x7f080021
			public static int ua_notification_button_tell_me_more = 2131230753;
			
			// aapt resource value: 0x7f080022
			public static int ua_notification_button_unfollow = 2131230754;
			
			// aapt resource value: 0x7f080023
			public static int ua_notification_button_yes = 2131230755;
			
			// aapt resource value: 0x7f080024
			public static int ua_ok = 2131230756;
			
			// aapt resource value: 0x7f080025
			public static int ua_retry_button = 2131230757;
			
			// aapt resource value: 0x7f080026
			public static int ua_select_all = 2131230758;
			
			// aapt resource value: 0x7f080027
			public static int ua_select_none = 2131230759;
			
			// aapt resource value: 0x7f080028
			public static int ua_share_dialog_title = 2131230760;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0c0000
			public static int Base_Widget_UrbanAirship_InAppMessage_Banner = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public static int Base_Widget_UrbanAirship_InAppMessage_Banner_ActionButton = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public static int Base_Widget_UrbanAirship_InAppMessage_Banner_ActionButtonContainer = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public static int Base_Widget_UrbanAirship_InAppMessage_Banner_DismissButton = 2131492867;
			
			// aapt resource value: 0x7f0c0004
			public static int Base_Widget_UrbanAirship_InAppMessage_Banner_Divider = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public static int Base_Widget_UrbanAirship_InAppMessage_Banner_Text = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131492870;
			
			// aapt resource value: 0x7f0c0007
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Container = 2131492871;
			
			// aapt resource value: 0x7f0c0008
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Date = 2131492872;
			
			// aapt resource value: 0x7f0c0009
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Icon = 2131492873;
			
			// aapt resource value: 0x7f0c000a
			public static int Base_Widget_UrbanAirship_MessageCenter_Item_Title = 2131492874;
			
			// aapt resource value: 0x7f0c000b
			public static int InAppMessage_Banner = 2131492875;
			
			// aapt resource value: 0x7f0c000c
			public static int InAppMessage_Banner_TextAppearance = 2131492876;
			
			// aapt resource value: 0x7f0c001e
			public static int LandingPageStyle = 2131492894;
			
			// aapt resource value: 0x7f0c000d
			public static int MessageCenter = 2131492877;
			
			// aapt resource value: 0x7f0c000e
			public static int MessageCenter_EmptyMessage_TextAppearance = 2131492878;
			
			// aapt resource value: 0x7f0c000f
			public static int MessageCenter_Item_Date_TextAppearance = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public static int MessageCenter_Item_Title_TextAppearance = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public static int MessageCenter_MessageNotSelected_TextAppearance = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public static int Widget_UrbanAirship_InAppMessage_Banner = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public static int Widget_UrbanAirship_InAppMessage_Banner_ActionButton = 2131492883;
			
			// aapt resource value: 0x7f0c0014
			public static int Widget_UrbanAirship_InAppMessage_Banner_ActionButtonContainer = 2131492884;
			
			// aapt resource value: 0x7f0c0015
			public static int Widget_UrbanAirship_InAppMessage_Banner_Card = 2131492885;
			
			// aapt resource value: 0x7f0c0016
			public static int Widget_UrbanAirship_InAppMessage_Banner_DismissButton = 2131492886;
			
			// aapt resource value: 0x7f0c0017
			public static int Widget_UrbanAirship_InAppMessage_Banner_Divider = 2131492887;
			
			// aapt resource value: 0x7f0c0018
			public static int Widget_UrbanAirship_InAppMessage_Banner_Text = 2131492888;
			
			// aapt resource value: 0x7f0c0019
			public static int Widget_UrbanAirship_MessageCenter_Item_CheckBox = 2131492889;
			
			// aapt resource value: 0x7f0c001a
			public static int Widget_UrbanAirship_MessageCenter_Item_Container = 2131492890;
			
			// aapt resource value: 0x7f0c001b
			public static int Widget_UrbanAirship_MessageCenter_Item_Date = 2131492891;
			
			// aapt resource value: 0x7f0c001c
			public static int Widget_UrbanAirship_MessageCenter_Item_Icon = 2131492892;
			
			// aapt resource value: 0x7f0c001d
			public static int Widget_UrbanAirship_MessageCenter_Item_Title = 2131492893;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public static int ua_notification_button_overrides = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int ua_notification_buttons = 2131034113;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BannerView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public static int BannerView_bannerActionButtonTextAppearance = 6;
			
			// aapt resource value: 4
			public static int BannerView_bannerDismissButtonDrawable = 4;
			
			// aapt resource value: 0
			public static int BannerView_bannerFontPath = 0;
			
			// aapt resource value: 5
			public static int BannerView_bannerNoDismissButton = 5;
			
			// aapt resource value: 2
			public static int BannerView_bannerPrimaryColor = 2;
			
			// aapt resource value: 3
			public static int BannerView_bannerSecondaryColor = 3;
			
			// aapt resource value: 1
			public static int BannerView_bannerTextAppearance = 1;
			
			public static int[] CardView = new int[]
			{
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public static int CardView_optCardBackgroundColor = 0;
			
			// aapt resource value: 1
			public static int CardView_optCardCornerRadius = 1;
			
			// aapt resource value: 2
			public static int CardView_optCardElevation = 2;
			
			public static int[] MessageCenter = new int[]
			{
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 7
			public static int MessageCenter_messageCenterDividerColor = 7;
			
			// aapt resource value: 6
			public static int MessageCenter_messageCenterEmptyMessageText = 6;
			
			// aapt resource value: 5
			public static int MessageCenter_messageCenterEmptyMessageTextAppearance = 5;
			
			// aapt resource value: 0
			public static int MessageCenter_messageCenterItemBackground = 0;
			
			// aapt resource value: 2
			public static int MessageCenter_messageCenterItemDateTextAppearance = 2;
			
			// aapt resource value: 8
			public static int MessageCenter_messageCenterItemIconEnabled = 8;
			
			// aapt resource value: 9
			public static int MessageCenter_messageCenterItemIconPlaceholder = 9;
			
			// aapt resource value: 1
			public static int MessageCenter_messageCenterItemTitleTextAppearance = 1;
			
			// aapt resource value: 4
			public static int MessageCenter_messageNotSelectedText = 4;
			
			// aapt resource value: 3
			public static int MessageCenter_messageNotSelectedTextAppearance = 3;
			
			public static int[] States = new int[]
			{
					2130771988};
			
			// aapt resource value: 0
			public static int States_ua_state_highlighted = 0;
			
			public static int[] TextAppearance = new int[]
			{
					2130771989};
			
			// aapt resource value: 0
			public static int TextAppearance_urbanAirshipFontPath = 0;
			
			public static int[] Theme = new int[]
			{
					2130771990,
					2130771991};
			
			// aapt resource value: 0
			public static int Theme_inAppMessageBannerStyle = 0;
			
			// aapt resource value: 1
			public static int Theme_messageCenterStyle = 1;
			
			public static int[] UAWebView = new int[]
			{
					2130771992};
			
			// aapt resource value: 0
			public static int UAWebView_mixed_content_mode = 0;
			
			public static int[] UrbanAirshipActionButton = new int[]
			{
					16842753,
					16842754};
			
			// aapt resource value: 1
			public static int UrbanAirshipActionButton_android_icon = 1;
			
			// aapt resource value: 0
			public static int UrbanAirshipActionButton_android_label = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
