#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int ua_iam_slide_in_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ua_iam_slide_in_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ua_iam_slide_out_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ua_iam_slide_out_top = 2130968579;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int bannerActionButtonTextAppearance = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int bannerDismissButtonDrawable = 2130771975;
			
			// aapt resource value: 0x7f010003
			public const int bannerFontPath = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int bannerNoDismissButton = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int bannerPrimaryColor = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int bannerSecondaryColor = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int bannerTextAppearance = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int inAppMessageBannerStyle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int mixed_content_mode = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int optCardBackgroundColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int optCardCornerRadius = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int optCardElevation = 2130771980;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int common_signin_btn_text_dark = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_signin_btn_text_light = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int ua_iam_primary = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int ua_iam_secondary = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int urban_airship_blue = 2131099660;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int ua_iam_banner_corner_radius = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ua_iam_banner_elevation = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ua_iam_banner_width = 2131230722;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_close_white_18dp = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_notification_button_accept = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_notification_button_cart = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_notification_button_copy = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_notification_button_decline = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_notification_button_download = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_notification_button_follow = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_notification_button_happy = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_notification_button_open_browser = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_notification_button_remind = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_notification_button_sad = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_notification_button_share = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_notification_button_thumbs_down = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_notification_button_thumbs_up = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_notification_button_unfollow = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_urbanairship_notification = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Icon = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int monoandroidsplash = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ua_iam_background = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ua_ic_close = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0009
			public const int action_button = 2131361801;
			
			// aapt resource value: 0x7f0a000d
			public const int action_buttons = 2131361805;
			
			// aapt resource value: 0x7f0a000c
			public const int action_divider = 2131361804;
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a000b
			public const int alert = 2131361803;
			
			// aapt resource value: 0x7f0a0003
			public const int always_allow = 2131361795;
			
			// aapt resource value: 0x7f0a000a
			public const int close = 2131361802;
			
			// aapt resource value: 0x7f0a0007
			public const int close_button = 2131361799;
			
			// aapt resource value: 0x7f0a0004
			public const int compatibility_mode = 2131361796;
			
			// aapt resource value: 0x7f0a0008
			public const int in_app_message = 2131361800;
			
			// aapt resource value: 0x7f0a0006
			public const int myButton = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int never_allow = 2131361797;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ua_iam_animation_duration = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ua_activity_landing_page = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ua_fragment_iam = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ua_fragment_iam_card = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ua_iam_button = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ua_iam_content = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050038
			public const int app_name = 2131034168;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int common_android_wear_notification_needs_update_text = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int common_android_wear_update_text = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int common_android_wear_update_title = 2131034127;
			
			// aapt resource value: 0x7f05001f
			public const int common_google_play_services_api_unavailable_text = 2131034143;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_enable_button = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_enable_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_enable_title = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_error_notification_requested_by_msg = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_install_button = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_install_text_phone = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_install_text_tablet = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_install_title = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_invalid_account_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_invalid_account_title = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_needs_enabling_title = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_network_error_text = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_network_error_title = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_notification_needs_update_title = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_notification_ticker = 2131034114;
			
			// aapt resource value: 0x7f050021
			public const int common_google_play_services_sign_in_failed_text = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int common_google_play_services_sign_in_failed_title = 2131034144;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_unknown_issue = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_unsupported_text = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_unsupported_title = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_update_button = 2131034139;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_update_text = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_update_title = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_updating_text = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_updating_title = 2131034130;
			
			// aapt resource value: 0x7f05001e
			public const int common_open_on_phone = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int common_signin_button_text = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int common_signin_button_text_long = 2131034141;
			
			// aapt resource value: 0x7f050037
			public const int hello = 2131034167;
			
			// aapt resource value: 0x7f050034
			public const int ua_channel_notification_ticker = 2131034164;
			
			// aapt resource value: 0x7f050022
			public const int ua_notification_button_accept = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int ua_notification_button_buy_now = 2131034147;
			
			// aapt resource value: 0x7f050035
			public const int ua_notification_button_copy = 2131034165;
			
			// aapt resource value: 0x7f050024
			public const int ua_notification_button_decline = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int ua_notification_button_dislike = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int ua_notification_button_download = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int ua_notification_button_follow = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int ua_notification_button_less_like = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int ua_notification_button_like = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int ua_notification_button_more_like = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int ua_notification_button_no = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int ua_notification_button_opt_in = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int ua_notification_button_opt_out = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int ua_notification_button_remind = 2131034158;
			
			// aapt resource value: 0x7f050036
			public const int ua_notification_button_save = 2131034166;
			
			// aapt resource value: 0x7f05002f
			public const int ua_notification_button_share = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int ua_notification_button_shop_now = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int ua_notification_button_unfollow = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int ua_notification_button_yes = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int ua_share_dialog_title = 2131034163;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_ActionButton = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_ActionButtonContainer = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_DismissButton = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_Divider = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Base_Widget_UrbanAirship_InAppMessage_Banner_Text = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int InAppMessage_Banner = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int InAppMessage_Banner_TextAppearance = 2131296263;
			
			// aapt resource value: 0x7f09000f
			public const int LandingPageStyle = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int Mono_Android_Theme_Splash = 2131296272;
			
			// aapt resource value: 0x7f090008
			public const int Widget_UrbanAirship_InAppMessage_Banner = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int Widget_UrbanAirship_InAppMessage_Banner_ActionButton = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int Widget_UrbanAirship_InAppMessage_Banner_ActionButtonContainer = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int Widget_UrbanAirship_InAppMessage_Banner_Card = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int Widget_UrbanAirship_InAppMessage_Banner_DismissButton = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int Widget_UrbanAirship_InAppMessage_Banner_Divider = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int Widget_UrbanAirship_InAppMessage_Banner_Text = 2131296270;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BannerView = new int[]
			{
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 6
			public const int BannerView_bannerActionButtonTextAppearance = 6;
			
			// aapt resource value: 4
			public const int BannerView_bannerDismissButtonDrawable = 4;
			
			// aapt resource value: 0
			public const int BannerView_bannerFontPath = 0;
			
			// aapt resource value: 5
			public const int BannerView_bannerNoDismissButton = 5;
			
			// aapt resource value: 2
			public const int BannerView_bannerPrimaryColor = 2;
			
			// aapt resource value: 3
			public const int BannerView_bannerSecondaryColor = 3;
			
			// aapt resource value: 1
			public const int BannerView_bannerTextAppearance = 1;
			
			public static int[] CardView = new int[]
			{
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int CardView_optCardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_optCardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_optCardElevation = 2;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] Theme = new int[]
			{
					2130771981};
			
			// aapt resource value: 0
			public const int Theme_inAppMessageBannerStyle = 0;
			
			public static int[] UAWebView = new int[]
			{
					2130771982};
			
			// aapt resource value: 0
			public const int UAWebView_mixed_content_mode = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
